### ISSUE TITLE
Plugin does not detect git repository correctly if .ssh/config file is used for host aliases

### ISSUE THREAD

**Issue by mirkosertic** [uwolfer/gerrit-intellij-plugin#104]
It seems that there is a problem if ssh in combination with .ssh/config file to define a host alias to clone a repository. The plugin fails to compare with Branch. It shows "Error: No repository found for Gerrit project: ..."

Any ideas?

**Comment by uwolfer** [comment]
Closing since my question is still unanswered. Feel free to report back.

**Comment by adriweb** [comment]
Same issue here with the latest version of everything, and having tried the mentioned tip (and more)

**Comment by lucanLepus** [comment]
a coworker just had this issue, caused by the remote-url containing a trailing slash - not sure how it got there but i decided to leave this comment here in case anyone else lands here when googling the error
