### ISSUE TITLE
Code review - comment dialog - suggestion overlap issue

### ISSUE THREAD

**Issue by ihorpts** [uwolfer/gerrit-intellij-plugin#127]
Hello

A suggestion window lays under comment dialog when you add comments in code review process. See screenshot below...

![overlap](https://cloud.githubusercontent.com/assets/7080319/4269060/8d3d27f2-3cb7-11e4-84e5-95ca1ef71f32.jpg)

**Comment by ihorpts** [comment]
@uwolfer - in IntelliJ IDEA 14.1.2 this issue is gone...

**Comment by uwolfer** [comment]
@ihorpts: Thanks for the update.
