### ISSUE TITLE
Rewrite Git push extension for IntelliJ 14

### ISSUE THREAD

**Issue by uwolfer** [uwolfer/gerrit-intellij-plugin#128]
Git push dialog got rewritten, see #105.

**Comment by gkrasnow** [comment]
I am still having issues when pushing to multiple repositories in IntelliJ v14 with plugin version 0.9.5.2.  Same issue as before.  One repository gets properly pushed for code-review, and the rest push to master instead of refs/for/master.

**Comment by uwolfer** [comment]
@gkrasnow: Please update to the latest version (released yesterday). This release addresses multi repo pushing.
