### ISSUE TITLE
Cannot show change: Git error occurred while getting commit. Please check if Gerrit is configured as remote for the currently used Git repository.

### ISSUE THREAD

**Issue by gbougeard** [uwolfer/gerrit-intellij-plugin#129]
I have multiple modules, each one has its own git repo.

When I want to see a change files I'm getting : 
Cannot show change: Git error occurred while getting commit. Please check if Gerrit is configured as remote for the currently used Git repository.

What do I have to check specifically?

**Comment by pvasilyev** [comment]
I had the same issue.
The IDE tuning, which helped me: I changed my git SSH settings for the IDE. My 'SSH executable' had "Built-in" value, but I changed to "Native" and it worked for me.

Turns out, that the Gerrit plugin just couldn't fetch any code/changes simply because of wrong ssh.

**Comment by uwolfer** [comment]
@pvasilyev: Thanks for posting your workaround.

For me, it also works with the "Build-in" ssh-executable. Do you have some special ssh / git settings on your system?

**Comment by pvasilyev** [comment]
Actually nothing special except the custom (non default) ssh-key for the gerrit server access.
So to have command line access I have following lines in my ~/.ssh/config
```
Host <gerrit-server>
Hostname <gerrit-server>
IdentityFile ~/.ssh/<custom-ssh-key>
```
