### ISSUE TITLE
remote: ERROR: missing Change-Id in commit message footer even when hooks installed

### ISSUE THREAD

**Issue by Janebcf** [uwolfer/gerrit-intellij-plugin#142]
Hi,

I have installed hooks using: scp -p -P 8766 muUsername@my.repo.branch:hooks/commit-msg/ .git/hooks/

But I still run into following error each time I do a git push origin HEAD:refs/for/master
I tried  git commit --amend to add the change-Id specified in the error, but it still fails.

**Comment by uwolfer** [comment]
Can you see a change-id for *every* commit in your git history (git log) which is not already available in your git remote?

**Comment by Janebcf** [comment]
No my latest commit log does not have a Change-Id. But I did run the hooks command.
All others commit have it.

**Comment by uwolfer** [comment]
Add the hook, then use "git commit --amend".

**Comment by Janebcf** [comment]
I already ran git commit --amend, added the change-Id from above error to it, but still it fails.

**Comment by uwolfer** [comment]
So the commit contains a change-id now? If not, you can manually "generate" a hash and add it in the correct format (just take an existing change-id and slightly modify it).

If it still fails, please check the "version control" tab in IntelliJ to see the full error message from your Gerrit server.

**Comment by Janebcf** [comment]
I see 2 change-Id now in my latest commit. But the older commit still misses a change-Id
I am trying to merge on the git prompt and not IntelliJ.

**Comment by uwolfer** [comment]
I hope you were able to resolve this issue. Closing this issue as it is not plugin specific.

**Comment by Janebcf** [comment]
I was able to resolve it the other day by basically doing a hard reset for my local branch and starting it over.
But I ran into the same issue again.
This time all my git log have a change-Id  but still same error.

**Comment by Janebcf** [comment]
I am aware that you solve plug-in issues, so would you be able to point me to a place where this issue can be solved?
Thanks in Advance

**Comment by uwolfer** [comment]
When you push to Gerrit and an error occurs, you should get an error message. Check the "version control" tab in IntelliJ to see the full error message from your Gerrit server.

**Comment by Janebcf** [comment]
I don't have access to The Gerrit server.

**Comment by uwolfer** [comment]
@Janebcf: You don't need access to server logs. You can do that in your IntelliJ IDE.
