### ISSUE TITLE
Can't login to gerrit with LDAP auth

### ISSUE THREAD

**Issue by esazhin** [uwolfer/gerrit-intellij-plugin#143]
Using pycharm 4.0.4 CE and plugin version 0.9.4 I can't login to the Gerrit instance:
specifying URL http://myserver:port
username and password and getting HttpStatusException Status code 401, content unauthorized

Update: It works when the HTTP password in Gerrit > USer Settings is set, but it couldn't understand LDAP password generally used for login into Gerrit GUI.

**Comment by uwolfer** [comment]
Normally you need to use the HTTP password which you set in Gerrit settings. In "special" setups which are protected by HTTP login, you need to provide the usermame / password which you enter in the HTTP login dialog.

Can I close this issue or do you need some help?

**Comment by esazhin** [comment]
I'm comparing the behavior of this plugin with Mylyn plugin for eclipse which starting from the version 3.14 has full support for Gerrit. Mylyn was able to connect using the LDAP password that Gerrit uses for authentication. That's why i got confused. If you think that it is worth spending time on making it to work the same way, then please leave it open, otherwise you can close it as the workaround is present.

Thank you for the plugin!

**Comment by uwolfer** [comment]
Ah, good to know that it works with Mylyn. So for sure we should support it as well.

Please let me know how LDAP authentication works in your case. Does a HTTP password dialog appear before you can access the web interface?

**Comment by uwolfer** [comment]
@esazhin: Or do you enter your LDAP credentials in a HTML-form (like https://git.eclipse.org/r/)?

**Comment by uwolfer** [comment]
I have added support for LDAP auth with HTML-form: https://github.com/uwolfer/gerrit-rest-java-client/commit/42cfd5e80b4b005f332726bc68a86984e9a0fc14

It will be included in the next release.

**Comment by uwolfer** [comment]
@esazhin: The current release supports LDAP auth. Feel free to test and post any feedback here.

**Comment by esazhin** [comment]
@uwolfer Hey sorry for the delay: i will double check that as soon as possible.
The LDAP auth on gerrit side that we are seeing is just an HTML page with user login and passowrd, on mylyn side i was able to configure that right in the plugin configuration parameters.

Thanks for the update!

**Comment by uwolfer** [comment]
The last release contains a problem: write-operations aren't supported. This is fixed with this change: https://github.com/uwolfer/gerrit-rest-java-client/commit/1b2af223d2b0dffb4dff266f92007e3c1fdbf04e which will be included in the next release.

**Comment by esazhin** [comment]
@uwolfer thank you very much for keeping this in the works. I'm very sorry for the inability to  respond fast to your questions or test stuff - we are behind firewall and bringing in new stuff is not a simple thing to do :(
