### ISSUE TITLE
Ctrl-Enter fails to close Add Comment popup when conflicting key mapping exists

### ISSUE THREAD

**Issue by rbbratta** [uwolfer/gerrit-intellij-plugin#144]
Pycharm 4.0.4
Gerrit plugin 0.9.5

When the IPython Notebook | Run cell in-place  command is mapped to Ctrl-Enter it prevents the Add Comment popup from closing.  I think IPython Notebook stuff was added in Pycharm 4.0, so maybe this is a new key mapping.

I removed the "Run cell in-place" key mapping and Ctrl-Enter works again.

![gerrit-plugin-fix](https://cloud.githubusercontent.com/assets/1276487/5862541/9ec57436-a227-11e4-8938-27548a1d33bb.png)

**Comment by uwolfer** [comment]
@rbbratta: Thanks for your report.

How do you suggest fixing this issue? Adding a button to save a comment? Or add a config option to set another keyboard shortcut?

**Comment by rbbratta** [comment]
A save and cancel button would be nice, and it would be more obvious I think.

At first I thought it was focus issue, since the popup seemed to lose focus when I alt-tabed, and the popup has no other window controls when you right-click on it.  This is on Fedora 20 with KDE, btw.

**Comment by rbbratta** [comment]
Thank you for the quick fix.  It works great.  :)
