### ISSUE TITLE
Could not fetch commit because no remote url matches Gerrit host

### ISSUE THREAD

**Issue by ArminVieweg** [uwolfer/gerrit-intellij-plugin#146]
I get two errors, when I try to click on an entry:

> Could not fetch commit because no remote url matches Gerrit host.
> Git repository: %s

and

> Git error occurred while getting commit. Please check if Gerrit is configured as remote for the currently used Git repository.

I have configured "pushInsteadOf" in git, with gerrit server.

**Comment by uwolfer** [comment]
@ArminVieweg: Please check out the following hint (3rd point):
https://github.com/uwolfer/gerrit-intellij-plugin#list-of-changes-is-empty

"pushInsteadOf" is not respected.

**Comment by ArminVieweg** [comment]
Do you mean with "add a remote" this?

![image](https://cloud.githubusercontent.com/assets/1275298/6092198/cc5e9e46-aed3-11e4-908f-dbcbbbcd5183.png)

Unfortunately I just get  a "Connection failed" error. "Failed to send channel request".

But maybe I am totally wrong.

**Comment by ArminVieweg** [comment]
Ah sorry. I am stupid ^^

You've meant a `git remote add TYPO3.CMS ssh://***@review.typo3.org:29418` in gitbash ^^

Well now I get just the second error "Git error occurred while getting commit..."

**Comment by uwolfer** [comment]
Do you get any additional messages? Please also check the "Version control"-tab in IntelliJ after you get this error.

**Comment by uwolfer** [comment]
@ArminVieweg: Please see my last comment.

**Comment by ArminVieweg** [comment]
Oh sorry!
Here is what version control says:

```

23:44:07.774: cd D:\vhosts\typo3master.local\.git
23:44:07.774: git -c core.quotepath=false fetch --progress Packages/TYPO3.CMS refs/changes/23/36823/1
fatal: Project not found: 
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
23:44:10.427: cd D:\vhosts\typo3master.local
23:44:10.427: git -c core.quotepath=false log b22d67df86b44be0cecc1631dea399e1b19253e2 -1 --pretty=format:%x01%H%x02%ct%x02%an%x02%at%x02%ae%x02%cn%x02%ce%x02%P%x02%s%x02%b%x02%B%x03 --encoding=UTF-8 -M --name-status -c --
fatal: bad object b22d67df86b44be0cecc1631dea399e1b19253e2


```

**Comment by uwolfer** [comment]
@ArminVieweg: Thanks. It looks like the first "cd" is wrong? It shouldn't change into "typo3master.local/.git". Would "typo3master.local/Packages/TYPO3.CMS" be correct?

**Comment by ArminVieweg** [comment]
No, this `D:\vhosts\typo3master.local\` is the root of the cloned repository.

**Comment by uwolfer** [comment]
@ArminVieweg: Thanks. Just to clearify: `D:\vhosts\typo3master.local\` is your clone directory of the project `Packages/TYPO3.CMS` (and not a subdirectory)?

**Comment by ArminVieweg** [comment]
Yes. Sounds like that the missing structure is the reason ;)

**Comment by uwolfer** [comment]
@ArminVieweg: I have just tried to rebuild your setup (with TYPO3) and it seems to work fine here.

The content I have added in ``.git/config``:
```
[remote "Packages/TYPO3.CMS"]
        url = https://review.typo3.org/Packages/TYPO3.CMS
        fetch = +refs/heads/*:refs/remotes/origin/*
```

Please change your ssh url with the https one for this remote. Since you are still pushing to "origin" (I assume), it won't hurt. This remote is just used for the Gerrit plugin.

Btw, what does your origin look like? For me the plugin also worked without adding a remote.

**Comment by uwolfer** [comment]
@ArminVieweg: Have you had time to check things as written in my feedback above?

**Comment by uwolfer** [comment]
@ArminVieweg: Would be great if you could confirm that my last comment helped. If it still does not work for you, I'd like to look into this issue once again.

**Comment by yareally** [comment]
@uwolfer: I'm not the reporter, but I had a similar issue and your suggestion resolved it.

**Comment by a-r-m-i-n** [comment]
Sorry for not responding! I'm not into this topic anymore. But great to see, that this post helped nevertheless :)
