### ISSUE TITLE
Add support for a reviewer to write comments in intellij

### ISSUE THREAD

**Issue by yairogen** [uwolfer/gerrit-intellij-plugin#150]
currently the plugin allows you as the owner of the change to reply on comments made by others. If you want to review changes created by others and write comments on the change - it is not possible.

**Comment by uwolfer** [comment]
It is possible to write file comments. You can right click a line in the diff browser or select a range and press the key "C". It opens a comment editor.

Again, documentation for the plugin is missing :(

**Comment by yairogen** [comment]
I tried to right click on the line number or near by - but not on the row itself.
thanks.
