### ISSUE TITLE
Cannot Login to Gerrit Server

### ISSUE THREAD

**Issue by Wy-Nasty** [uwolfer/gerrit-intellij-plugin#154]
Hello,

I am very interested in using the gerrit intellij plugin. Unfortunately I am stuck at the very beginning... Being able to login to the gerrit server via the plugin. I know the credentials are correct since I can login via the web page (in chrome). But I cannot do it through the plugin in intellij.  I tried using both the password I have set for gerrit and the HTTP-Password. I get a couple of things given the different urls I enter. The main url should be (and this isn't the actual url) http://our-gerrit-site.com/gerrit/login. But I've also tried it with removing login which is just the main gerrit page. I get a few things...

com.google.gerrit.extensions.restapi.RestApiException: Request failed.

or

com.urswolfer.gerrit.client.rest.http.HttpStatusException: Request not successful. Message: Forbidden. Status-Code: 403

or

com.urswolfer.gerrit.client.rest.http.HttpStatusException: Request not successful. Message: Unauthorized. Status-Code: 401.

I really want to use this, maybe you guys know of a solution? Thank you for the help

**Comment by uwolfer** [comment]
@Wy-Nasty: You need to use the URL without "/login", i.e. "http://our-gerrit-site.com/gerrit". Do you know how the logins are managed (e.g. LDAP)? Do you get an HTTP access dialog from browser or a login HTML page from Gerrit?

What version of Gerrit would you like to connect to?

**Comment by Wy-Nasty** [comment]
I tried the the "http://our-gerrit-site.com/gerrit" as well and got the same results regardless of the password I use (HTTP or LDAP). I receive the HTTP access dialog from the browser. There isn't an html login page. We are using Gerrit 2.5.2

**Comment by uwolfer** [comment]
@Wy-Nasty: Gerrit < 2.6 is not supported by this plugin.

README content: "Only Gerrit 2.6 or newer is supported (missing / incomplete REST API in older versions)."

**Comment by shohaghcsesust** [comment]
why it's not supported old versions like gerrit 2.1.6.1 ?

**Comment by uwolfer** [comment]
@shohaghcsesust 
README content: "Only Gerrit 2.6 or newer is supported (missing / incomplete REST API in older versions)."

**Comment by shohaghcsesust** [comment]
Is it possible to fix this issue?

**Comment by uwolfer** [comment]
> Is it possible to fix this issue?

Nope, this is not really possible without rewriting a lot of existing code. And it does also not make sense IMHO because Gerrit < 2.6 is really old and not supported anymore. I suggest you (or your admin) to update the Gerrit instance.

**Comment by liyongjun1** [comment]
I have the same problem. I always can't login successfully with the http password. After I change the password to my usual one, it succeessed immediately.
