### ISSUE TITLE
Does the current version of the plugin not work with IntelliJ 14.1?

### ISSUE THREAD

**Issue by gkrasnow** [uwolfer/gerrit-intellij-plugin#155]
I accidentally upgraded to 14.1 today and noticed that I no longer see any of the gerrit configuration, windows, etc.

**Comment by uwolfer** [comment]
Yes, it does. You need to update the plugin.

Please note that the new oneside diff viewer is not supported for viewing comments yet. You need to switch to the default one.

**Comment by igreenfield** [comment]
I don't see new version in the repository

**Comment by uwolfer** [comment]
If you have manually installed the plugin via zip, you probably need to uninstall and then reinstall it. Please try it that way.

**Comment by igreenfield** [comment]
OK thanks.
