### ISSUE TITLE
Re-login after session timeout

### ISSUE THREAD

**Issue by sjelen** [uwolfer/gerrit-intellij-plugin#168]
After the current session times out, the plugin does not login again, but shows an error - "Failed to get Gerrit changes. Request not successful. Message: Forbidden. Status-Code: 403. Content: Must be signed-in to use reviewer:self.". 
This requires restarting IntelliJ to login again.
Intellij 14.1.1, Gerrit plugin 0.9.6.2

**Comment by ihorpts** [comment]
+1
it becomes annoying...

**Comment by uwolfer** [comment]
What authentication method do you use?

If you can reproduce this issue with an public Gerrit instance, please post a link where I can test.

**Comment by uwolfer** [comment]
Please also post the Gerrit version.

**Comment by uwolfer** [comment]
Fixed: https://github.com/uwolfer/gerrit-rest-java-client/commit/b0af6e4317cab111e1dae1f644f5bec9694a6c88

I would like to verify this fix once requested information is provided.

**Comment by sjelen** [comment]
Gerrit version is 2.8.1, I use password authentication using https.

**Comment by seh** [comment]
I'm suffering this same problem using version 0.9.6.2 of the plugin. Thanks for fixing it, @uwolfer. How often do you publish updates for IDEA's plugin manager to pick up?

**Comment by uwolfer** [comment]
@seh: You can expect an update in the next few days.
