### ISSUE TITLE
How post answers to comments

### ISSUE THREAD

**Issue by igreenfield** [uwolfer/gerrit-intellij-plugin#177]
How I can post my answers to review comments from the plugin?

**Comment by uwolfer** [comment]
When you open a file diff, you can click on the comment icons. There you can select "Reply" or "Done".

If this is not what you are looking for, please tell me.

**Comment by igreenfield** [comment]
This not solve the problem: as this only put the reply into “Draft Comments” and then I post it from gerrit UI.

I need the post feature!

Thanks

**Comment by uwolfer** [comment]
You can post comments from the plugin: right-click on change in list -> "Review" -> "0" (if you just want to post comments without a rating).

**Comment by igreenfield** [comment]
The flow is:

1.       I create review

2.       Someone replay with comments

3.       I want to replay to that comments…

How I can do that from the plugin?

**Comment by uwolfer** [comment]
If you want to reply to e file comment, you need to do it as I have written above. If you want to reply with a "general" comment, you can do it this way: right-click on change in list -> "Review" -> "0..."  (please note the "...").

**Comment by griels** [comment]
Just stumbled on this again, but in fact it does seem to submit comments.
You just don't see them until you hit reply to the comment post in question in the Gerrit web UI.

**Comment by griels** [comment]
![image](https://user-images.githubusercontent.com/1263585/56734719-8bffe900-675b-11e9-92b8-0b0cabe19cb8.png)
![image](https://user-images.githubusercontent.com/1263585/56734788-bb165a80-675b-11e9-8b18-6c8972e66a8e.png)

**Comment by ssadoun** [comment]
> When you open a file diff, you can click on the comment icons. There you can select "Reply" or "Done".
> 
> If this is not what you are looking for, please tell me.

Is it possible that there are no "comment icons" while using the plugin through PyCharm?
