### ISSUE TITLE
Plugin does not sign in again after the web session timed out

### ISSUE THREAD

**Issue by cg-d** [uwolfer/gerrit-intellij-plugin#178]
I started using the plugin and it worked quite nicely (after my workaround in #12 was in place). I sent my laptop to sleep and now the plugin does not work anymore because it will not try again to login to gerrit. It just shows me the 400 and basically forces me to restart IDEA :-/

**Comment by uwolfer** [comment]
@cg-d: What's the version of your Gerrit instance?

**Comment by cg-d** [comment]
2.11

**Comment by uwolfer** [comment]
This is a bug when using the plugin against a Gerrit 2.11 server. I have fixed this issue - but the fix will only be available in Gerrit 2.12: https://gerrit-review.googlesource.com/#/c/67464/

If you have access to Gerrit server configuration, you can extend web session timeout:
https://gerrit-review.googlesource.com/Documentation/config-gerrit.html#cache ("web_sessions").

**Comment by AlexJF** [comment]
This seems to have resurged?

Gerrit URL: https://review.gerrithub.io (version at the time of writing: 2.13.3-1753-g8e7a8e4)

Gerrit toolbox in IntelliJ shows no changes. Selecting 'Me' in Owner filter results in:

```
18:07	Failed to get Gerrit changes.: Request not successful. Message: Bad Request. Status-Code: 400. Content: Not Signed In.
```

**Comment by uwolfer** [comment]
@AlexJF: What version of IntelliJ are you using?

**Comment by AlexJF** [comment]
2016.3. In fact, I think the issue came up right after the upgrade although I can't be certain.

**Comment by uwolfer** [comment]
@AlexJF: IntelliJ 2016.3 changed a lot in password safe handling. Can you please try to re-enter the password in settings? And probably check if the workarounds in issue #248  help in your case?

**Comment by AlexJF** [comment]
Just reentering the password didn't work. What did appear to work (at least until now) was:

1. Settings->Appearance & Behaviour->System Settings->Passwords, chossing "Do not save". 
2. Restart IntelliJ
3. Settings->Appearance & Behaviour->System Settings->Passwords, reselect "In Native Keychain"

**Comment by uwolfer** [comment]
Can you still reproduce this issue?

**Comment by uwolfer** [comment]
Please add a comment if you still can reproduce this issue.
