### ISSUE TITLE
Cannot Login to Gerrit Server in phpstorm 9.0

### ISSUE THREAD

**Issue by zhang-bin** [uwolfer/gerrit-intellij-plugin#181]
Hello:
     I install the gerrit plugin version: 0.9.7.1-141 in my phpstorm, but when i test login our gerrit server, it alarm: 
can't login to https://our-gerrit-server.com:18086 com.google.gerrit.extensions.restapi.RestApiException Request Failed. 

    phpstorm version: 9.0
    gerrit plugin version: 0.9.7-141 
    gerrit server version: 2.11

btw: when i use phpstorm 8.0.3, it's ok!

Sorry for my poor english and thank you for your help!

**Comment by uwolfer** [comment]
@zhang-bin: Can you please try to enter the password / username in Gerrit IntelliJ plugin settings again and click the "Test" button? I have not used phpstorm 9 yet, but I also have not heard of issues with it from other users.

**Comment by zhang-bin** [comment]
Got same error: can't login to https://our-gerrit-server.com:18086 com.google.gerrit.extensions.restapi.RestApiException Request Failed.

Whatever i enter correct or incorrect username/password, always get same error.

Perhaps i use https gerrit server?

**Comment by uwolfer** [comment]
@zhang-bin: Does your Gerrit server have a valid SSL-certificate? I.e. does the browser accept the certificate without ignoring warnings?

**Comment by yabawock** [comment]
I've got the same problem with PhpStorm 9.0 on OSX. Firefox & Safari are both happy with the certificate on https://review.typo3.org

**Comment by zhang-bin** [comment]
I found this error happened on OSX. My colleague use phpstorm 9.0 on Windows 7, and everything is ok!

**Comment by uwolfer** [comment]
What version of Java are you using? Have you updated it recently?

**Comment by zhang-bin** [comment]
Aha! It's my mistake, my phpstorm use java version 1.6*,1.7+, and when i change it to 1.8*, the gerrit plugin run successfully!

@uwolfer  Thank for you help!!!

@yabawock Maybe you can edit '/Applications/PhpStorm.app/Contents/Info.plist', and find JVMVersion key, modify its value to your java version, good luck for you!

**Comment by yabawock** [comment]
I'm using the OS X Version with the bundled JRE 1.8 (1.8.0_40-internal-b82 x86_64, JVM OpenJDK Server 64 bit by JetBrains s.r.o)

I just got the Update notification for PhpStorm 9.0.1 - will try that and report back.

**Comment by yabawock** [comment]
Update: Upgrading to PhpStorm 9.0.1 with the bundled JRE solved it for me. Testing the connection was successful.

**Comment by uwolfer** [comment]
Thanks for your feedback. I'm happy that you've got it solved. :)
