### ISSUE TITLE
Cannot fetch changes: No fetch information provided.

### ISSUE THREAD

**Issue by Syphon86** [uwolfer/gerrit-intellij-plugin#186]
Hi,

if i click on a review in the gerrit plugin, PHPStorm shows me following error message:

"Cannot fetch changes: No fetch information provided. If you are using Gerrit 2.8 or later, you need to install the plugin 'download-commands' in Gerrit."

In gerrit (2.11.3) the 'download-commands'-plugin is installed. 

Do you know how the gerrit plugin must be configured to work properly?

Thank you for your help.

**Comment by uwolfer** [comment]
Is the Gerrit instance available in public for testing? Are you absolutely sure that the download command plugin is inatalled (i.e. can you see download urls in the web UI)?

**Comment by Syphon86** [comment]
Hi,

the gerrit server is not available in public.

I can see the download url in the web UI
![gerrit_download](https://cloud.githubusercontent.com/assets/3044847/9710967/f5ba453e-553f-11e5-8e55-a07fccc03f40.PNG)

**Comment by Syphon86** [comment]
Hi,

is it a problem that we just have activated the ssh option to checkout the reviews from gerrit?

Which method does the plugin need to fetch does informations?

**Comment by uwolfer** [comment]
Is the Git fetch url equal to the web UI url (host only) you have entered in the settings? Gerrit uses the REST API for getting data.

**Comment by uwolfer** [comment]
@Syphon86: Can you please answer my question above?

**Comment by Syphon86** [comment]
Hi,

my admin now added the http scheme for the command download plugin and now the plugins works correctly.

I think it would help other users if you mention this in your documentation.

Thank you for your help.

**Comment by uwolfer** [comment]
@Syphon86: Thanks for reporting. There is a hint about this issue: https://github.com/uwolfer/gerrit-intellij-plugin#list-of-changes-is-empty

Do you think it needs any improvements to be more clear?

**Comment by pavelkornev** [comment]
@uwolfer we have same issue as mentioned above:
"Cannot fetch changes: No fetch information provided. If you are using Gerrit 2.8 or later, you need to install the plugin 'download-commands' in Gerrit."

HTTP and SSH are both activated. Download-commands plugin is also installed.

We can see change list, but we could see details of the change and as a result we could easily checkout change from the Gerrit within this plugin.

Is there anyway I can get more detailed debug information from the plugin regarding REST requests to the Gerrit server?

**Comment by pavelkornev** [comment]
BTW: colleagues on Windows don't have this issue. It occurs only on OSX

Screenshot - https://s24.postimg.org/84m7os9lf/webstorm_gerrit_plugin.png

**Comment by uwolfer** [comment]
@pavelkornev: Are you sure that your colleagues (where it works) and you both have installed the latest plugin version (IntelliJ settings, refresh list of plugins)? Have you tried with the same Gerrit changes?

> Is there anyway I can get more detailed debug information from the plugin regarding REST requests to the Gerrit server?

The easiest way to debug this would be to look into Gerrit server request logs.

When you access the Gerrit web UI, can you see the "Download" button top right with Git download URLs (like "Checkoug")?

**Comment by pavelkornev** [comment]
@uwolfer

1. Yes, we both have installed latest versions of WebStorm (v2016.3.2) and Gerrit plugin (v0.9.9.1-146). Gerrit version on the server is v2.12.5-prod-4. The only difference in our configurations is operating system. I'm using OSX Sierra (10.12.1), my colleagues are on Win10.

2. Yes, we have tried on the same changes. They can see change details - I can't. But I can see list of changes as you can see on the screenshot above, that said plugin partly works.

3. Yes, "download-commands" plugin is installed in our Gerrit and links are available on top right corner (proof - https://s27.postimg.org/9p67eah8j/gerrit.png)

Please let me know if I can provide any additional information in order to understand and reproduce this bug.

**Comment by uwolfer** [comment]
@pavelkornev: I do not really have an idea what's going wrong... Sorry. If you find the time, you could checkout this plugin and run it in IntelliJ in debug mode.
