### ISSUE TITLE
Add link to markdown syntax help

### ISSUE THREAD

**Issue by sschuberth** [uwolfer/gerrit-intellij-plugin#198]
When writing  a message to abandon a change, the hint below the form says "Write your comment here. You can use a simple markdown-like syntax". It would be nice if the words "markdown-like syntax" would link to a help / web page explaining the supported syntax.

**Comment by uwolfer** [comment]
@sschuberth: Thanks for your suggestions.

Do you think the following guide would help? I have not found anything Gerrit specific, but most things should work.
https://guides.github.com/features/mastering-markdown/

This seems to be Gerrit specific, but IMHO not in a condition that could be used as reference: https://gist.github.com/dlebech/62b69ee7c9fdb53c63a6.

Probably it would also be worth adding a guide to the Gerrit documentation and link that.

**Comment by sschuberth** [comment]
Hi @uwolfer! Based on the information from the Gist I've created a change for upstream Gerrit to document the three supported markdown-like elements: https://gerrit-review.googlesource.com/74494

Once this gets merged, the correct link would be: https://gerrit-review.googlesource.com/Documentation/user-review-ui.html#summary-comment

Although the `summary-comment` anchor does not exist yet in the current Gerrit documentation, you could still already use that link as non-existing anchors simply get ignored, and IMO `user-review-ui.html`, even in its current state, is the most fitting official Gerrit documentation regarding the markdown-syntax supported in comments as it at least mentions the block quote element.

**Comment by uwolfer** [comment]
Thanks @sschuberth for your great efforts here! I will add this link once the googlesource.com Gerrit setup gets updated with this doc update.
