### ISSUE TITLE
Support deleting / publishing draft changes

### ISSUE THREAD

**Issue by sschuberth** [uwolfer/gerrit-intellij-plugin#199]
When looking at draft changes (by using the "Status: Drafts" filter) and right-clicking on any of the drafts, the context menu shows "Abandon". However, draft changes can only be deleted, not abandoned, and trying to do so yields this error message:

    Failed to abandon Gerrit change.
    com.urswolfer.gerrit.client.rest.http.HttpStatusException: Request not
    successful. Message: Conflict. Status-Code: 409. Content: draft changes cannot
    be abandoned.

So for draft changes, please change the context menu to say "Delete" instead of "Abandon", and use the [Delete Draft Change](https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#delete-draft-change) endpoint instead.

**Comment by sschuberth** [comment]
On a related note, also instead of "Submit" we should have "Publish" for draft changes.

**Comment by sschuberth** [comment]
Thanks! Looking forward to trying it out in a new release :-)

**Comment by uwolfer** [comment]
@sschuberth: I have released a release-candidate which contains these features. See #34.

**Comment by sschuberth** [comment]
@uwolfer Publishing / deleting drafts seems to work fine. The only thing I noticed is that doing so does not automatically refresh the list view to reflect the new status. Is this by intention?

**Comment by uwolfer** [comment]
@sschuberth: Right, it does not refresh after any action yet. I have created #216.
