### ISSUE TITLE
Empty git roots marked to be pushed by default

### ISSUE THREAD

**Issue by Krzychek** [uwolfer/gerrit-intellij-plugin#201]
When "push commits to Gerrit by default" is enabled, on push action all git roots gets marked to be pushed, even though there's no commits to push in them.

**Comment by ihorpts** [comment]
+1
And I'd add group select check box to be able to check/uncheck all "items" in one go. It's sometimes too much clicking there: 

![push_to_gerrit](https://cloud.githubusercontent.com/assets/7080319/12848366/c1776fb2-cc19-11e5-94a0-b830ad84574e.jpg)

**Comment by eekboom** [comment]
Duplicate of #182
