### ISSUE TITLE
This plugin brokes phpStorm

### ISSUE THREAD

**Issue by akimvital** [uwolfer/gerrit-intellij-plugin#204]
After installing this plugin and restarting phpStorm in doesn't start. It just shows error 
![image](https://cloud.githubusercontent.com/assets/615439/14210856/9d37ebb8-f833-11e5-85fc-841e43b78602.png)

But from another user phpStorm still starts ok (there is no this plugin).

**Comment by uwolfer** [comment]
I don't think this issue is related to this plugin. Can you reproduce this issue? I.e. disable it -> verify it works; enable it -> verify it fails with this error? Please post your results - I will reopen this issue in that case.
