### ISSUE TITLE
Checkout branch deletes local changes

### ISSUE THREAD

**Issue by zeratul021** [uwolfer/gerrit-intellij-plugin#205]
Just want to ask if this is a bug or a feature.

Currently when you have local changes in a branch that you checked out from Gerrit via the plugin they will be lost when different revision / branch is checked out. Without a warning.

I'd expect that when I'm fiddling with changes in a branch that I've just checked out from Gerrit my changes will be kept there. Or at least ask/warn me that my local changes will be lost if I checkout.

Thanks for the comments.

**Comment by eekboom** [comment]
Happened to me, too. Hooray for IDEA's local history!

**Comment by uwolfer** [comment]
I'm not able to reproduce this issue. When I have local change and try to check out a change, I get an error balloon:

> Checkout Error
> error: Your local changes to the following files would be overwritten by checkout:
> TEST2.txt
> test/test.iml
> Please, commit your changes or stash them before you can switch branches.
> Aborting

What's the exact workflow to reproduce this issue? Also, what version of IntelliJ are you using?

**Comment by eekboom** [comment]
Hi, I tested a lot and found it to be easily reproducible:
- Checkout master.
- Delete all local review branches.
- Make a change in any file X that is not even touched by some gerrit change Foo.
- In the Gerrit tool window use the context menu for "Foo" to checkout foo.
- X is still changed - fine so far
- Checkout master again (changed X is still there)
- Again use the Gerrit tool window to checkout Foo
  => Change in X is gone.

So it seems that if you already have a local branch for the current patch set of a gerrit change, then a switch to that branch deletes all local changes.

(BTW using IDEA itself to checkout the local branch works fine, local changes are preserved. However I don't usually keep track of my local review branches and the specific patch sets they are on.)

**Comment by uwolfer** [comment]
@eekboom: Thanks a lot for the detailed reproduction steps. I did not remember that this "feature" was introduced with a pull request a long time ago. Will release a new version which includes this fix soon.
