### ISSUE TITLE
Allow filtering by 'Project' name

### ISSUE THREAD

**Issue by nshavitt** [uwolfer/gerrit-intellij-plugin#208]
Typing the name of the project does the filter buy the project , but then user can not filter by text in the commit.  Nice to allow the user filtering by 'Project'

**Comment by uwolfer** [comment]
Workaround: type in the filter text field `project:my-project`.

**Comment by uwolfer** [comment]
You do not even need the workaround written above. Just select "All" in the "Branch" filter for a specific project.
