### ISSUE TITLE
ssh and https dont work over VPN

### ISSUE THREAD

**Issue by rovkinmax** [uwolfer/gerrit-intellij-plugin#220]
I can connect to gerrit server only with vpn. I'm use Cisco anyconnect.
From browser and terminal has access. But from plugin settings 'requet failed' when test connection.
I just press "test" and at the first onset show error dialog with message `google.gerrit.extensions.restapi.restapiexception: request failed`

When I try connect over https, throw exception `com.urswolfer.gerrit.client.rest.http.HttpStatusException: Request not successful.  
Message: Not found.   
Status-code: 404.   
Connect: Not Found.`

But all credentials correct. Example,  from SourceTree all working and ssh and https

**Comment by uwolfer** [comment]
Do you have a proxy configuration in IntelliJ?
Also, the error message could point out that you are using a wrong URL for your Gerrit in IntelliJ. Please make sure that you enter the URL including path when Gerrit does not run on root (e.g. Eclipse Gerrit runs on https://git.eclipse.org/r/, which means that you need to enter the full address including (/r).

**Comment by rovkinmax** [comment]
Sorry, this is my mistake. It was necessary to use the domain url, but I used a reference to the repository.
If it is not in manual, please add it. This will save somebody's day :)
