### ISSUE TITLE
Does not work with latest IntelliJ (2016.2)

### ISSUE THREAD

**Issue by tgrip** [uwolfer/gerrit-intellij-plugin#221]
On opening the plugin in the latest edition, which is still in beta, there comes an error with NoSuchMethod

**Comment by uwolfer** [comment]
@tgrip: Do you have installed the latest version of the plugin? Please refresh the list of plugins in IntelliJ settings and check if an update is available.

**Comment by tgrip** [comment]
I couldn't update the plugin, even when I tried to refresh it.
I could fix it by uninstalling and installing it again
