### ISSUE TITLE
List of changes is empty

### ISSUE THREAD

**Issue by jacaru** [uwolfer/gerrit-intellij-plugin#232]
Cloned through File->New->Project from Version Control->Gerrit
Gerrit settings URL is https://git.opendaylight.org/gerrit
Git remote is ssh://[user]@git.opendaylight.org:29418/sfc

Project [changes](https://git.opendaylight.org/gerrit/#/q/project:sfc) on gerrit web show a bunch of  them when logged in as myself.

On intelliJ, list of changes is empty with all filters set to All. I have got no errors nor any meaningful log. Checked the [tips](https://github.com/uwolfer/gerrit-intellij-plugin#list-of-changes-is-empty) and I seem to comply with all of them. Gerrit settings test is succesful.

Oposed to #222, I never get a list of changes. 

IntelliJ 1016.1.3
Gerrit 0.9.8.1

**Comment by uwolfer** [comment]
@jacaru: I have tried to reproduce this issue, but I'm not able to do so. It works fine for me. I'm not logged in and use https for Git access: https://git.opendaylight.org/gerrit/sfc

Can you please try it also with https? It is probably related to the suffix "/gerrit" which is non-existing in your remote url.

**Comment by jacaru** [comment]
I added the remote https://git.opendaylight.org/gerrit/sfc and it now works. I am now a bit confused about how should my workflow look like since I still don't know how the plugin is used. Could I still use the original remote for everything and just have this new dummy remote to spoof the gerrit plugin?

**Comment by uwolfer** [comment]
@jacaru: Yes, you can still use the ssh remote. The remote with identical url as used for the plugin is just to match repos in Gerrit.
