### ISSUE TITLE
Login gerrit failed

### ISSUE THREAD

**Issue by TommyLike** [uwolfer/gerrit-intellij-plugin#239]
I had an issue when I tried to login gerrit with http username and password at site(https://review.openstack.org/openstack/cinder.git)
## These are what I have done and what I get:

Pycharm settings(Version Control/Gerrit)

```
Login.URL:https://review.openstack.org/openstack/cinder.git  
Login.Login:${my_username} #copied from https://review.openstack.org/#/settings/http-password  
Login.Password:$(my_password) #copied from https://review.openstack.org/#/settings/http-password  
```

when clicked Test Button,the error message showed:**Can't login to https:........ Request failed**

But,I tried in my git-review code, and I set environment:  
git remote add gerrit https://{username}:{password}@review.openstack.org/openstack/cinder.git
and I tried **git review -l**, it's works well,what is the difference and why I failed in Pycharm?

Thanks

**Comment by uwolfer** [comment]
Use as url just this: https://review.openstack.org

**Comment by TommyLike** [comment]
Thanks it works

**Comment by TommyLike** [comment]
@uwolfer I find I can't commit in files and lines,and it seems that https://review.openstack.org  has meet the gerrit requirements(now is 2.11):

```
File and line based comments (Gerrit 2.7 or newer only)
```

I thought the right place should be:Gerrit Panel/Select/Compare with Branch/Select File/Show Diffes/Add Comments on files.So what's wrong with this?Can I add comments on files

**Comment by uwolfer** [comment]
@TommyLike: You can just comment to diffs of changes (select change, open diff view in right panel, then select code and press the key C. Is that what you are looking for?

**Comment by TommyLike** [comment]
Thanks again~,it works well
