### ISSUE TITLE
Blank gerrit tool window in latest 2016.3 EAP

### ISSUE THREAD

**Issue by eekboom** [uwolfer/gerrit-intellij-plugin#241]
I installed the EAP from the usual place, i.e. https://confluence.jetbrains.com/display/IDEADEV/IDEA+2016.3+EAP
I started with a clean state (removed .IntelliJ... folders in my home dir, did not let IDEA import any old settings).
After installing gerrit and configuring it, the tool window stays blank.
The connection in the gerrit settings was successfull and I even get a balloon notification about a pending gerrit change.
Yet the gerrit tool window is completely blank/gray.

**Comment by uwolfer** [comment]
@eekboom: Before you configured, the (empty) list was visible? Can you please check if CPU load is high (i.e. it hangs at some point)?

**Comment by eekboom** [comment]
No, it was just gray without any content right from the start. I opened the IDE settings and navigated to the gerrit settings.

I did not notice any CPU load but cant say right now for sure. Will check tomorrow.

I had hoped this would be easy to reproduce because it happened directly after installing the plugin (and restarting) with a fresh install of IDEA.

**Comment by uwolfer** [comment]
@eekboom: Please not that I have not tried to reproduce it yet. Will do it when I find time.

**Comment by kunickiaj** [comment]
Observed the same thing as well. Currently on EAP 2016.3 build 163.6110.12

**Comment by hobbes38111** [comment]
I have the same issue. I haven't noticed any CPU spikes, and as far as I can tell, the plug-in is connecting to gerrit, as I get notifications about pending reviews. Everything seems normal, aside from display.

IntelliJ IDEA (Community Edition) 2016.3 EAP
Build #IC-163.6110.12, built on October 12, 2016
JRE: 1.8.0_112-release-b408 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

latest gerrit plugin version.

**Comment by donsim** [comment]
Same issue with 
IntelliJ IDEA (Community Edition) 2016.3 EAP
Build #IC-163.6512.17, built on October 19, 2016
JRE: 1.8.0_112-release-b403 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by uwolfer** [comment]
I was able to reproduce this issue and will try to fix and release an update ASAP.

**Comment by uwolfer** [comment]
I have just pushed a new release. If IntelliJ does not notify you, you can reload the list of plugins manually and right click the plugin item to update it.
