### ISSUE TITLE
There are two same menu item In the code review menu

### ISSUE THREAD

**Issue by pipiliang** [uwolfer/gerrit-intellij-plugin#244]
Hi, there are two same menu item in the code review menu:
![2](https://cloud.githubusercontent.com/assets/15980794/19543519/a73c403a-96aa-11e6-9999-5e1ce47b5647.PNG)

**Comment by uwolfer** [comment]
@pipiliang: They do not exactly the same thin: "+2" sends the voting directly while "+2..." opens a dialog which allows to enter a message which is sent together with the voting.
