### ISSUE TITLE
Status is all list is empty

### ISSUE THREAD

**Issue by zhouliangshun** [uwolfer/gerrit-intellij-plugin#246]
Hello, Default status is all, But not list my commit. When I change status to 'Open', There can see my commit. So I thinlk this is a bug.My IDE is Android Studio 2.2.2. And the plugin version is 0.9.9.1-142.

**Comment by uwolfer** [comment]
@zhouliangshun: What's the version of your Gerrit server? You can find the version number in the footer of the web UI.

**Comment by zhouliangshun** [comment]
My Gerrit version is 2.8.3

**Comment by uwolfer** [comment]
@zhouliangshun: I think this is a limitation of your Gerrit server. You can verify it by searching for `is:open OR is:merged` in the search bar top right in Gerrit web UI. If this search also does not show your commit, it is not an issue of this plugin.

**Comment by zhouliangshun** [comment]
@uwolfer you are right. the webside not support "OR". So the plugin can change to the all status quey string is "",Mabye this can working for this Gerrit Server.

**Comment by uwolfer** [comment]
@zhouliangshun: An empty query seems not to work - at least not for gerrit-review.com: https://gerrit-review.googlesource.com/changes/?q=
When the `q`-Parameter is omitted, only open changes are returned.

Feel free to try it with your Gerrit instance.
