### ISSUE TITLE
Full error message not shown when push rejected by Gerrit server

### ISSUE THREAD

**Issue by vivganes** [uwolfer/gerrit-intellij-plugin#253]
When I push a commit and let's say push is rejected by the Gerrit server, the plugin does not show the error given by the Gerrit server.

I have a server that rejects any commit without changeid.  Now, when I push using the plugin, I do not get the full message that the server gives while I am able to see the server's response while pushing from git command line.

**Comment by uwolfer** [comment]
Please see #212. This is something that should be handled by IntelliJ Git support. See also referenced JetBrains issues and feel free to vote / comment there.
