### ISSUE TITLE
Password is not remembered between IDE restarts

### ISSUE THREAD

**Issue by xko** [uwolfer/gerrit-intellij-plugin#254]
Happens on IDEA 2016.3 Utimate on both linux and windows

**Comment by uwolfer** [comment]
@xko: What's your config option for saving passwords?

See: https://www.jetbrains.com/help/idea/2016.3/handling-passwords-for-git-remote-repositories.html#passwordPolicy

**Comment by xko** [comment]
Oops. Overlooked that completely.
Thanks for the hint! Problem solved
