### ISSUE TITLE
Login failure: Can't login to https://... .git com.google.gerrit.extensions.restapi.RestApiException: Expected JSON but got 'text/html; charset=UTF-8'

### ISSUE THREAD

**Issue by Wizzy-wooz** [uwolfer/gerrit-intellij-plugin#264]
Hi guys!

Can you pls help? I have an issue with Intellej Idea Gerrit plugin.  When I try to connect to Gerrit I get:
Login failure: Can't login to https://... .git com.google.gerrit.extensions.restapi.RestApiException: Expected JSON but got 'text/html; charset=UTF-8'. How to deal with such issue?

Best regards,
Elena

**Comment by uwolfer** [comment]
This is most probably a configuration issue. Have you pasted the Gerrit web UI main (root) URL into plugin config?

**Comment by Wizzy-wooz** [comment]
Fixed. Wrong url. Thanks for hint. Have a nice day!

**Comment by uwolfer** [comment]
@Wizzy-wooz: What's the version of your Gerrit server?
