### ISSUE TITLE
Cannot check out another change with the same topic

### ISSUE THREAD

**Issue by eekboom** [uwolfer/gerrit-intellij-plugin#267]
When a change has a topic set and I check out the change using the plugin (right-click on change, checkout), then the plugin creates a local branch, that is named after the author and topic, for example review/stephen/some-topic

When I now try to checkout another change from the same author and having the same topic, then the change *is not checked out*: I remain on my local branch containing the previous change.

This is very confusing and error prone.

What is the intended behaviour?
Updating/resetting the topic branch to the new change?
Creating a new local branch, with the change id/patch-set as suffix (or just incrementing a number as suffix)?

Some pointers where to start looking would be nice. Maybe I can try to create a patch.

**Comment by uwolfer** [comment]
I think it should not change an existing local branch. I would prefer to use a new branchname, which includes "more" details in name like short change-id or / and patch set number.

Starting point: CheckoutAction#buildBranchName

**Comment by eekboom** [comment]
This problem is not only related to having the "topic" set. It only happens more frequently in that case.

The same bug occurs, if no topic is set:

* I check out the latest patch set of a change - branch name is <changeNumber>
* A colleague fixes something in that change and pushed a new patch set
* I try to checkout the new patch set
=> Same bug occurs, because when I try to check out the latest patch set, the patch set is not included in the name, so it gets the old name.

I propose to always use topic (if set), change number and patch set, for example

review/name/topic-#change-patch

The branch names get a little longer, but that's better than the bug where I end up on a local branch that is different from what I tried to check out.

Also I like the fact that I can clearly match the branch name with a specific change and patch.

Unfortunately there is https://youtrack.jetbrains.com/issue/IDEA-73669 which makes longer branch names appear truncated in the status bar.

Other ideas - taking more effort, maybe later?
Check hashes of local branches against remote ones to re-use local branches.
Configurable branch name pattern.

**Comment by uwolfer** [comment]
Please see #133. The initial idea was IMHO to create branch name with the same pattern as `git-review` uses.

Probably it's worth looking into `git-review` how it handles this situations?

**Comment by eekboom** [comment]
The git-review docs say:

> $ git review -d 2033
> This will download the change, put it in a branch called review/AUTHOR/TAG (if the change has no tag, the sequence number will be used instead), and switch to that branch.

So I think we already use a different format.

But you are right one could check how git-review would then handle a subsequent checkout of a specific change set using "git review -d 2033,4"

Anyway, we need to find a way to avoid this nasty bug (#230, #235, #267).
