### ISSUE TITLE
Make "Project" column optional

### ISSUE THREAD

**Issue by eekboom** [uwolfer/gerrit-intellij-plugin#268]
In the plugin setting "List all Gerrit changes (instead of changes from currently open project only)" is un-checked by default and I guess most users are happy with that default.

So: Why should I see a "Project" column in the changes list? It is always the same project that I have opened anyway.

The Project column just takes space away that could be used for other columns like "Change #" and "topic".

I'll create a pull request soon, if this change is OK with you.

**Comment by uwolfer** [comment]
"Project" column makes sense when using IntelliJ with a multiple repo setup. You can checkout multiple repositories in IntelliJ in the same project. But I agree, in many setups, this column does not make any sense.

Probably there could be a setting for enabling / disabling this column?

**Comment by eekboom** [comment]
Yes, exactly. That's what I meant by "Make Project column optional".

I would add another checkbox in the plugin setting for the Project column. Default value would be true/checked.

**Comment by eekboom** [comment]
I created a patch that introduces a setting "Show Project Column".
However it's not a checkbox, but a combo box with value "Always", "If project has multiple repositories" and "Never" with default value being "If project has multiple repositories".
What do you think about this in general?

The code needs some more testing (I don't currently have a multi-repo project at hand) and some polishing. Especially the way I pass project into GerritChangeListPanel feels wrong.
See https://github.com/eekboom/gerrit-intellij-plugin/commit/d0840f3820daacafb417922d650bb3fc58b4393c

**Comment by eekboom** [comment]
I forgot the option "List all Gerrit changes(instead of changes from the currently open project open)".
That should also make the Project column visible in "automatic" mode.

**Comment by uwolfer** [comment]
I like the idea. Most users will be happy with auto-mode, but adding a setting should not hurt.

I think there is no better way of "injecting" `Project` (there is no Guice binding available for it).
