### ISSUE TITLE
Drafts don't show up

### ISSUE THREAD

**Issue by cr22rc** [uwolfer/gerrit-intellij-plugin#272]
I see all Status open, merged etc just fine.  But status Drafts is empty and I know I have Drafts in gerrit
Anyone else see this? Are there any hints suggestion on how get them listed ?

My pluggin version is Version: 0.9.9.1-146

**Comment by uwolfer** [comment]
@cr22rc: What's the version of your Gerrit server? IIRC Gerrit older than 2.8 or 2.9 does not support draft queries.

**Comment by uwolfer** [comment]
@cr22rc: Due to missing feedback, I'm closing this issue. Feel free to add feedback.

**Comment by cr22rc** [comment]
Hi -- sorry for the supper late response. :)  My gerrit version is now 2.14.2 .  Really like this plugin but drafts still don't show up for me. :(  Now using 1.0.1-146 Is there some trace I can provide that would help?

**Comment by cr22rc** [comment]
If I use the filter for Me it doesn't show anything also .. maybe related ?

**Comment by cr22rc** [comment]
I just notice with the Me filter as Owner I see a 
9:03 AM	Failed to get Gerrit changes.: Request not successful. Message: Bad Request. Status-Code: 400. Content: Not Signed In.

**Comment by cr22rc** [comment]
If I put in the Owner filter an explicit search for my id it works -- but no Drafts.

**Comment by uwolfer** [comment]
@cr22rc: I assume you have entered your credentials in the Gerrit plugin settings? Are you using a HTTP password which you have set in Gerrit web UI?

**Comment by cr22rc** [comment]
yes -- All works fine just that drafts don't show up.

**Comment by uwolfer** [comment]
@cr22rc: Are you using a HTTP password which you have set in Gerrit web UI?

**Comment by cr22rc** [comment]
@uwolfer yes - would any other credentials give me the other results which are working fine ?

**Comment by uwolfer** [comment]
@cr22rc: It depends on your setup. If you have other credentials for logging in into the web UI (e.g. some single sign on solution), you could try them also.

If your Gerrit instance is public, please let me know the URL so I can try it by my own.

**Comment by cr22rc** [comment]
yes -- All works fine just that drafts don't show up.

**Comment by cr22rc** [comment]
https://gerrit.hyperledger.org/r/#/dashboard/self

**Comment by cr22rc** [comment]
I just checked in my configuration the link there is actually https://gerrit.hyperledger.org/r
Not sure how I came up with that.  Once again, everything seems to work for me except drafts.

**Comment by cr22rc** [comment]
Is there some means to get you a log output of the request / response ?

**Comment by cr22rc** [comment]
I stand corrected.   I login with my Linux Foundation ID  I thought I had set up a http password but now relooking I'm not seeing that option even :(

![image](https://user-images.githubusercontent.com/15130714/29822168-8a645242-8c98-11e7-99f0-3540f7720355.png)

**Comment by uwolfer** [comment]
@cr22rc: Can you please try to use KeePass (https://www.jetbrains.com/help/idea/passwords.html) in IntelliJ password settings and enter the password again in the plugin? Then restart IntelliJ and try again. Would be great if you could try that. Afterwards, you can switch back to the standard password safe in IntelliJ.

**Comment by cr22rc** [comment]
I had an http pass set as mentioned above I know I did that.  Drafts never showed up.  They've moved gerrit to later release and I can't even find the option to set http password now.  So I just reset in the gerrit plugin configuration the password to my current linux foundation password and it seems Drafts now show up.  Odd

**Comment by uwolfer** [comment]
@cr22rc: Thanks, I'll close it.
