### ISSUE TITLE
Login failed code:401

### ISSUE THREAD

**Issue by luofengyeer** [uwolfer/gerrit-intellij-plugin#273]
Hello ~
I am very interested in this plugin, this plugin feels very easy to use.When i was using it , I get a problem: I set up in AndroidStudio Setting ->
URL: http: //tom@gerrit.xx.com/a/All-User
Login: tom
Password: I Use the HTTP Password
But the login failed, prompt: 401, unauthorized,
Password fill me in the webUI login using the password is the case, may I ask this configuration is correct, thank you very much~

**Comment by uwolfer** [comment]
Try as URL http://gerrit.example.com

**Comment by luofengyeer** [comment]
Thanks ! This problem is solved~
