### ISSUE TITLE
Problems with remote X display

### ISSUE THREAD

**Issue by kaldonia** [uwolfer/gerrit-intellij-plugin#274]
We are working on an central development server with redirected X display to each developers local client machine. The server is a Debian linux jessie running the latest CLion (2017.1.1) with your plugin (0.9.9.1-146) enabled and being successfully setup (Test Connection button works). Gerrit version is 2.12 with plugin download-commands installed.

We also have some developer using a local debian machine with the same setup (same Linux, same CLion and your gerrit plugin) showing no problems. When he is doing a remote X session the same problems appear as on the development server.

Some of the error messages appearing: 

> No fetch information provided. If you are using Gerrit 2.8 or later, you need to install the plugin 'download-commands' in Gerrit.

> Request not successful. Message: Forbidden. Status-Code: 403. Content: Must be signed-in to use reviewer:self.

**Comment by uwolfer** [comment]
@kaldonia: I think this is not related to your X display redirection setup. Can you please check out #140 and see if these hints help in your case?

**Comment by kaldonia** [comment]
Indeed, it was not related to remote X server. Thanks to your hints and googling the follow up error messages we can now use the *very* useful plugin.

Steps that make it work for me:

- install `gnome-keyring` and setting up CLion to use native keychain ( #248 )
  - the password was disappearing after using Test button
  - now with the proper keychain, the password dots persist after testing the connection
- another error could be resolved by using native ssh, instead of build-in ssh in the Git tab ( #129 )
