### ISSUE TITLE
Cannot Code Review In Gerrit UI

### ISSUE THREAD

**Issue by SpaceStarX** [uwolfer/gerrit-intellij-plugin#277]
![capture](https://cloud.githubusercontent.com/assets/28698936/26051752/b96c3de4-3995-11e7-8065-f4063c9b491d.PNG)
I want to Code Review the Code someone commited , but the button is grey.
Could you tell me how to set up ?

**Comment by uwolfer** [comment]
You are most probably not logged in. Please check Gerrit plugin settings in Intellij if there is an username and a password set.

**Comment by SpaceStarX** [comment]
I did login in and it test successfull 
![image](https://cloud.githubusercontent.com/assets/28698936/26087946/970b0a32-3a26-11e7-83f3-d3409f710783.png)

**Comment by SpaceStarX** [comment]
These functions are still disabled, could you help me solve this problem? Thank you.

**Comment by uwolfer** [comment]
@yang837157632: When you restart IntelliJ, are these settings still present?

**Comment by SpaceStarX** [comment]
Yes, these settings are still present

**Comment by hoangcao** [comment]
I have the same problem. Waiting for instructions to be able to do code review. Thank you

**Comment by hoangcao** [comment]
I am able to do code review. The problem come from HTTP password. You may need to generate password and copy to the version control's gerrit to login properly.

**Comment by SpaceStarX** [comment]
Thank you, I am able to do code review, too.
