### ISSUE TITLE
Gerrit plugin for Pycharm does not find the Gerrit server

### ISSUE THREAD

**Issue by Formartha** [uwolfer/gerrit-intellij-plugin#283]
Hi,
I'm trying to access our local gerrit server with using http URL. for some reason, it keeps stating that it can't find the site (error 504 - Unable to locate server named XXXX) - but ping is working as well as accessing via web browser.

After switching the name record to IP, it says that I can't login - the error message is access denied which of course is incorrect because I had generated an HTTP password and it works perfectly with using git plugin.

I'm working on windows 7, Pycharm is updated to the latest version (2017.1.5) & Gerrit plugin is updated as well (1.0.0.1-146). The Gerrit server version is 2.9.1.

Hopefully someone could help me :)

**Comment by uwolfer** [comment]
@Formartha Can you access the Gerrit web UI when you enter this URL in your webbrowser?

**Comment by Formartha** [comment]
@uwolfer - the issue could be closed. the IT folks had been implemented new proxy.pac which caused the issue. reverting it back solved it :+1:
