### ISSUE TITLE
How to append shell ?

### ISSUE THREAD

**Issue by erstens** [uwolfer/gerrit-intellij-plugin#293]
eg:
```
git clone ssh://xxx@gerrit.xxx.com:29418/All-Projects && scp -p -P 29418 xxxx@gerrit.xxx.com:hooks/commit-msg All-Projects/.git/hooks/
```
thanks

**Comment by uwolfer** [comment]
The hook is installed automatically if you use the IntelliJ checkout action (VCS -> Checkout from VCS -> Gerrit).
Please add a comment if this is not what you want.
