### ISSUE TITLE
Settings are saved in General settings instead of Project ones

### ISSUE THREAD

**Issue by AMorgaut** [uwolfer/gerrit-intellij-plugin#295]
I go to the **project settings** from **project A**

1. I expand "Version Control"
2. I select Gerrit

The Webstorm Settings dialog shows the breadcrumb 

> **Version Control > Gerrit** [] For current project

I **fill and save** my project A gerrit settings

The Gerrit plugin works well in project A

___

I go to the **project settings** from **project B**

I **fill and save** my project B gerrit settings (different gerrit server, login & password)

The Gerrit plugin works well in project B
 
___

I go back to project A

* The Gerrit plugin is now connected via Project B settings
* Project A gerrit settings are lost

___

Notes:

* If I look into the ".idea" project folder, there is no gerrit settings
* if I look in my user Webstorm settings folder:
    * I see a `config/options/gerrit_settings.xml` file
    * Ii contains my last project gerrit server settings

___

So,
The Webstorm settings dialog is clearly lying for writing "For current project" and showing the "project" flag on the "gerrit" settings item

Supporting different gerrit servers is mandatory in my situation

Please....

PS: 
I'm using Webstorm 2016.1.3
With Gerrit plugin 1.0.4-142

**Comment by uwolfer** [comment]
Thanks for your detailed report.

You are right, the title "For current project" is wrong. This is unfortunately something I cannot change with plugin API (at least I have not found a way to do so). All settings panels in menu "Version control" show this text, but I think it is wrong for many others (e.g. also Git settings, which are developed by JetBrains, see https://youtrack.jetbrains.com/issue/IDEA-144811).

Nevertheless you are not the first user who has requested the settings to be saved per project. While I think this is a good idea, I just have not had the time to implement it yet. See also #159.

I'm always happy to get pull requests for such features.
