### ISSUE TITLE
How to send the accepted commit to remote server

### ISSUE THREAD

**Issue by Etesyolk** [uwolfer/gerrit-intellij-plugin#297]
Hi, I'm using the gerrit-intelij plugin and i don't understand some point. I entered  a new path(ssh://gerrit_uName@gerrit_host:29418/gerrit_projectName: refs/for/master) in intelij and all my commits are being pushed to gerrit server, the reviewers are checking it and submitting. But how are these changes are getting the remote(gitswarm) server? In which point of process I'm inserting the remote path?
Thanks.

**Comment by uwolfer** [comment]
I do not know your infrastructure. Normally, Gerrit is used as Git repo. If other users are cloning the repo from Gerrit, they should get your commits after you have submitted them in Gerrit.

If you need to synchronize it with another Git remote, you need to setup some type of synchronization. I think there are plugins for this task, but I have never configured it.

I think this question is something for the Gerrit community (chat or mailing list): https://www.gerritcodereview.com/#get-in-touch

**Comment by Etesyolk** [comment]
uwolfer : Thank you for the quick response. I think that gerrit replication is  exactly what i need.
