### ISSUE TITLE
Notification for new review displayed but list empty

### ISSUE THREAD

**Issue by wedi** [uwolfer/gerrit-intellij-plugin#300]
Hi,
I have installed your Gerrit plugin and am experiencing a strange behaviour: when I open Android Studio I get a message that there are commits waiting for my review but the list of changes is empty.

- Testing the login with the test button in the settings works.
- The configured git remote hostname matches the remote url configured in the Gerrit settings (except `/p/projectname` of course).
- I have added a remote named `projectname` as well.
- Displaying changes of all projects works.
- I can work with git in Studio and the version control tab displays the git tree. So I think I have correctly configured git in the IDE.
- When I open Android Studio I get notifications for my open reviews in all projects. Even if I have not configured to display changes of all projects.

Is there any other configuration I have missed?

Gerrit Plugin Version: 1.0.4-146
Android Studio 3.0.1
Gerrit Version: 2.13

![bildschirmfoto 2017-11-29 um 13 34 42](https://user-images.githubusercontent.com/1466269/33377283-3b5187da-d511-11e7-9a0c-15e65a27598b.png)

**Comment by uwolfer** [comment]
@wedi: Id you open plugin settings and check the option "List all Gerrit changes", does the list display you changes?

**Comment by wedi** [comment]
yes, that does work. But then I get notified of changes in every project not just the one I am currently interested in. I have edited the question to clarify what I have tested.

**Comment by uwolfer** [comment]
> The configured git remote hostname matches the remote url configured in the Gerrit settings (except /p/projectname of course).

What do you mean with the "/p/projectname"? Can you please post example URLs for both Git und Web?

**Comment by wedi** [comment]
Here you are:
- Gerrit configuration URL: `https://git.host.com/gerrit`
- Remote URL: `https://git.host.com/gerrit/p/projectname`

Thank you for looking into this!

**Comment by uwolfer** [comment]
In my case, the Git remote URL looks like this:
ssh://user@review.example.com:29418/projectname

Can you please try this? You can find the your RL in project settings in Gerrit: https://review.example.com/#/admin/projects/projectname

**Comment by uwolfer** [comment]
@wedi: Was you able to resolve this issue?

**Comment by wedi** [comment]
Sorry for the delay. 🤓 I haven‘t found the time to check with cloning via SSH yet. HTTPS is a standard way to do it, too.
I will come back to you!

**Comment by nzamani** [comment]
Very interesting - I updated my gerrit Plugin in WebStorm today, after that I could not see any changes anymore. After having struggled abot 2 hours I uninstalled the gerrit plugin, then I uninstalled WebStorm, I deleted the .WebStorm folder in my Home Dir (Win 8.1). Finally I made a clean install of WebStrom, then I installed the gerrit plugin. After this I checked out a project from Gerrit via ssh url, and guess what: it suddenly worked. I can't really explain this, but maybe you could try this as well...

**Comment by locosmike** [comment]
It seems like the plugin tries to determine the project name by stripping the value of _Web-URL_ from the project URL. Like @wedi described, our project URLs look like https://git.host.com/gerrit/p/projectname. If we add a remote to the project and change the URL to https://git.host.com/gerrit/projectname, the changes for the current project are correctly shown by the plugin. However, the invalid remote causes other issues. For example, SourceTree fetches from all remotes by default and then throws an error for the new remote because the project URL is invalid.

**Comment by uwolfer** [comment]
@isotes: Do you think this issue is also resolved with your PR #324?

**Comment by isotes** [comment]
Yes. This is exactly the same behavior I have encountered and solved with the PR.

**Comment by uwolfer** [comment]
@isotes: great!

**Comment by locosmike** [comment]
@isotes Thank you very much for fixing this issue :)
@uwolfer Please let me know when the changes from the PR will be integrated into the main version that is available in the IntelliJ plugin repository

**Comment by uwolfer** [comment]
I have just pushed a new release which contains the referenced PR.
