### ISSUE TITLE
Unable to connect to Gerrit

### ISSUE THREAD

**Issue by abhishekkishore** [uwolfer/gerrit-intellij-plugin#301]
I'm unable to establish a Gerrit connection. I've tried both ssh:
![image](https://user-images.githubusercontent.com/6493088/33645241-c6eac87a-da6f-11e7-8d7b-99f149cce91e.png)
and http:
![image](https://user-images.githubusercontent.com/6493088/33645282-f73dfa06-da6f-11e7-8809-b8b32c29598b.png)
Different errors, but both fail.
I'm moving from Eclipse to Intellij, and the connections have been working fine on Eclipse(EGit) for a long time now.

**Comment by uwolfer** [comment]
Please try the HTTP URL (2nd screenshot), but remove everything behind the slash.

**Comment by abhishekkishore** [comment]
Thank you for the response.
Do you mean I should try removing the "http://" from the url? Tried it. It gets added automatically when the focus moves out of the textbox. Same error afterwards.
To be clear, this is where I'm getting my connection details from.
![image](https://user-images.githubusercontent.com/6493088/33651889-62838a98-da8d-11e7-87fe-d109a44b7c76.png)
The message indicates incorrect credentials, so I don't suspect an issue with the internet connection proxy.
Also, is ssh not supported?

**Comment by uwolfer** [comment]
> Do you mean I should try removing the "http://" from the url? 

No, at the end. use: http://ci-gerrit....net/

**Comment by abhishekkishore** [comment]
That worked. Thank you!
Great plugin, btw.
