### ISSUE TITLE
Add gerrit group to reviewers

### ISSUE THREAD

**Issue by vladimirovcharov** [uwolfer/gerrit-intellij-plugin#302]
Hi!

I have IntellijIdea 2017.3 with latest Gerrit plugin. How can I add Gerrit group (for example named My Group) to reviewers? For now I can only add all emails separated with comma. I tried to use different quates and It didn't work.

Thanks!

**Comment by uwolfer** [comment]
I have never tried it, but it should work. You need to enter the group ID which you can find in group admin site: https://review.example.org/#/admin/groups/

Please post any feedback here (also if it works so I can close it).

See:
https://gerrit-review.googlesource.com/Documentation/rest-api-groups.html#group-id
https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#reviewer-input

**Comment by vladimirovcharov** [comment]
I tried to add UUID of the group and It didn't work. Got the error:

refs/for/feature/myfeature%r=951f6a6e08beb1d70f4ca1c21d489dac0ae0bec7	[remote rejected] (user "951f6a6e08beb1d70f4ca1c21d489dac0ae0bec7" not found)

Also, It didn't work with the name of the group that's unique and has space in it's name - MY Group. Unfortunately we have group names only with spaces and I can't check name without space.
Can It be the problem with configuration of our Gerrit server?

When I tried to use %20 instead of space I got strange behavior in the field reviewers looks like a bug, I can't even explain it, strange things with characters because of % symbol. And after this behavior I can't open Push window again. I need to restart my IDE to push again.

**Comment by uwolfer** [comment]
Ah, you are talking about adding reviewers in the the push dialog. It is possible that groups are not supported there - at least I cannot find anything about that in the official documentation: https://gerrit-review.googlesource.com/Documentation/user-upload.html#reviewers
Feel free to request this feature in the official Gerrit issue tracker.

You can add reviewers after pushing the commit with a right click in the Gerrit tool window list. Please let me know if that works for you.

**Comment by vladimirovcharov** [comment]
Yes, It works. I'll try to request this feature in the official Gerrit issue tracker. 
You can close this issue. 
Thanks for fast responses!
