### ISSUE TITLE
Failed to post Gerrit review

### ISSUE THREAD

**Issue by FelipeeDev** [uwolfer/gerrit-intellij-plugin#312]
I'm working in PHPStorm and I can push to Gerrit without any problems.

But when I'm only trying to send my review (using context menu i.e.: Review/Code Review/-1) I'm always getting:

```
Failed to post Gerrit review
com.urswolfer.gerrit.client.rest.http.HttpStatusException: Request not successful. Message: Not Found. Status-Code: 404. Content: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
404 Not Found
Not Found				
The requested URL /a/changes/my-vendor/my-package~my-branch~Ie...28/revisions/95...e4/review was not found on this server.
Apache/2.4.7 (Ubuntu) Server at my-gerrit.host Port 80
```

EDIT:
When I'm trying to add a comment to the code in the diff window I'm getting also this:

```
Failed to save draft comment: com.google.gerrit.extensions.restapi.RestApiException: Expected JSON but got 'text/html; charset=iso-8859-1
```

**Comment by uwolfer** [comment]
I assume that the URL entered in the Gerrit IntellIJ plugin settings is not correct. You must paste the URL you are using in the webbrowser to access the web UI. Can you please check that?

**Comment by FelipeeDev** [comment]
Yes! That was the problem. I've type http and didn't expect that it won't redirects to https. When I've changed to https problem's gone.
Thanks for help!
