### ISSUE TITLE
Difficulty logging in

### ISSUE THREAD

**Issue by stwwalton** [uwolfer/gerrit-intellij-plugin#313]
Configuration:
Gerrit plugin v1.0.6-146
IntelliJ v2017.2.5
Gerrit v2.13.9
MacBook Pro - OS v10.13.3

I use IntelliJ for my IDE and not able to successfully login the Gerrit plugin. Have tried both HTTP and SSH urls for the project, both return "Login Failure" 401, Unauthorized. From command line can use either url and successfully clone the project.

The login attempts are by clicking the "Test" button in the Login section of the Preferences...->Version Control -> Gerrit dialog.

Any help would be appreciated. Thanks!

**Comment by uwolfer** [comment]
@stwwalton: Are you using the URL you are using in the browser for the Gerrit web UI in the address field?

**Comment by stwwalton** [comment]
@uwolfer: Yes, I got the URL from the Gerrit Web UI and the password is from Gerrit Web UI user->Settings->HTTP password.

**Comment by uwolfer** [comment]
Could you also try the credentials you are using for the web UI login?
Do you know what type of authentication your Gerrit instance is using (htaccess, single sign on, ...)?

**Comment by stwwalton** [comment]
Our Gerrit instance uses single sign-on. Web UI login credentials yield same unauthorized.

**Comment by uwolfer** [comment]
You could try debugging your connection as described here:
https://gerrit-review.googlesource.com/Documentation/dev-rest-api.html

Please let me know your results.

**Comment by stwwalton** [comment]
(Logs removed)

**Comment by stwwalton** [comment]
[Results Here](https://github.com/uwolfer/gerrit-intellij-plugin/files/1858221/debugPlugin.txt)

**Comment by uwolfer** [comment]
@stwwalton: Thanks for your logs (I have removed them because they are not by interst for other people). It looks like a issue with your credentials, not related to the plugin. I know from other people in your company which are using the Gerrit IntelliJ plugin - so I assume that it is related your setup. I suggest your to ask around how others have set it up. I think I cannot help you in this case.

**Comment by stwwalton** [comment]
Problem solved, it was a user error. The Web-URL is the url of Gerrit not the url of the project.
