### ISSUE TITLE
	Cannot show change: Git error occurred while getting commit. Please check if Gerrit is configured as remote for the currently used Git repository.

### ISSUE THREAD

**Issue by yuanliwei** [uwolfer/gerrit-intellij-plugin#315]
Git error occurred while getting commit. Please check if Gerrit is configured as remote for the currently used Git repository.

Fetch failed: ssh variant 'simple' does not support setting port

git --version
git version 2.16.2.windows.1

**Comment by uwolfer** [comment]
You should use native ssh in IntelliJ.

See also: https://stackoverflow.com/a/48415043
