### ISSUE TITLE
Failed to get Gerrit changes.: Request not successful. Message: Bad Request. Status-Code: 400. Content: too many terms in query.

### ISSUE THREAD

**Issue by ericclone** [uwolfer/gerrit-intellij-plugin#326]
The credentials are good. I can get:
Gerrit Changes waiting for my review: (snipped...)

**Comment by uwolfer** [comment]
@ericclone: How many sub projects are in your IntelliJ project where you can reproduce this issue?

**Comment by ericclone** [comment]
I don't know. How can I check the number of sub projects in my intellij project? I am guessing maybe a few dozens? Oh and I am using CLion but that should not be a problem?
Sorry I don't understand the "where" part. Where as in what URL?

**Comment by uwolfer** [comment]
The plugin loads by default only changes which belong to one of the sub-projects which are loaded in IntelliJ / CLion. I assume that there are too many sub-projects in your case which leads in a too long url. You can try to disable this option in the plugin settings. Please let me know if that helps.

**Comment by ericclone** [comment]
Are you talking about "List all gerrit changes (instead from changes from currently open project only)"?
I unchecked this box already.

**Comment by uwolfer** [comment]
> Are you talking about "List all gerrit changes (instead from changes from currently open project only)"?

Yes.

Do you have access to the Gerrit server logs which could tell you the URL the plugin is trying to access in your setup?

I've also found this issue, which is probably related: https://bugs.chromium.org/p/gerrit/issues/detail?id=4904&desc=2 (but the fix should be included in recent Gerrit versions).

**Comment by ericclone** [comment]
Unfortunately I don't have access to the server log. Is it possible to enable some sort of debug logging from the client side to see the URL?
Our Gerrit server is at 2.15.3 which is only 1 minor version behind the latest 2.15.4 so it should contain the fix?

**Comment by uwolfer** [comment]
You can enable request logging in your IDE: Help -> Debug Log Settings... -> add "gerrit" (without quotes) on a new line.
Then you can find all requests in system/log/idea.log.

**Comment by ericclone** [comment]
It is a URL containing all the projects (I did not know I have 293 projects in this directory, most of them are 3rd-party dependencies). The URL is 11000 characters long. Is it possible to only query projects that directly contains files that are currently open, or something like whitelist/blacklist? In my case that would be no more than 2.

**Comment by uwolfer** [comment]
Thanks for your analysis.

Are these 293 projects all in the IntelliJ modules list (i.e. can you see them in the list of modules when you open "Project structure" dialog in IntelliJ?

I still think the option "List all Gerrit changes (instead from changes from currently open project only)" should work in your case (or at least it would not lead in failed requests).
When this option is disabled (which is the default), the plugin takes all Git repos which are in your current project and appends their name to the project query (see https://github.com/uwolfer/gerrit-intellij-plugin/blob/intellij14/src/main/java/com/urswolfer/intellij/plugin/gerrit/rest/GerritUtil.java#L363).

Are all of your 293 Git repos available in Gerrit?

Another idea would be to just take the "root" repo of your project. Would that work in your case (you can see the root repo in IntelliJ "Version control" settings  marked as "<Project>".

**Comment by ericclone** [comment]
It seems that CLion doesn't have a project structure menu item.
Even if it did, the project I am working on only has an empty "root" project and everything useful is part of some sub-project. Among these sub-projects, 2, may 3, are real projects that we currently work on. Others are just dependencies. 
Is there a shortcut to override this?
```
List<String> projectNames = getProjectNames(remotes);
```
 https://github.com/uwolfer/gerrit-intellij-plugin/blob/intellij14/src/main/java/com/urswolfer/intellij/plugin/gerrit/rest/GerritUtil.java#L374

**Comment by ericclone** [comment]
Surprise!!
I CHECKED "List all gerrit changes (instead from changes from currently open project only)" and the results are coming back.
I am be completely wrong but is it possible that the exclamation mark on this line should be removed?
https://github.com/uwolfer/gerrit-intellij-plugin/blob/intellij14/src/main/java/com/urswolfer/intellij/plugin/gerrit/rest/GerritUtil.java#L290

**Comment by uwolfer** [comment]
Oh, I have not read your first response about the "List all gerrit changes..." thing. You need to **check** this box in order to disable filtering by projects (it is unchecked by default). This will display any change for your configured Gerrit instance. Do you think this option is misleading? Do you think we could use a clearer label?
Can you use the plugin now with this option enabled? Or do you still think some sort of whitelist / blacklist would be a good idea?

**Comment by ericclone** [comment]
Nah. This works for me as is. Just need to remind myself to check the box. No need for whitelist / blacklist.

I think there is some interesting interaction between Gerrit and the plug-in.
- When the box is checked, it tells Gerrit "give me whatever you have" so it does not contain a project list. This somehow worked with our Gerrit server and produces the exact results I am looking for.
- When it's unchecked, it tries to "filter" projects by adding all 293 project names to the query string. Our Gerrit server does not like that.

I think my case is a rare situation.

In terms of the plugin, I think the function seems to be fine but maybe add something to the UI string "Note: Check this if you have many Gerrit projects in the same directory and are getting "too many terms" error" or something similar.

Thank you so much for the help!!

**Comment by uwolfer** [comment]
@ericclone: Thanks for your support. I have added now a hint to the README and settings dialog how to work around this error.
