### ISSUE TITLE
How to change geiit console font?

### ISSUE THREAD

**Issue by wangruihuano** [uwolfer/gerrit-intellij-plugin#332]
There are some chinese can not display,I want to try use another font.But I don't know how to change font for this ![gerrit console](https://graph.baidu.com/resource/1a575b2b8658bbbc69bef01541213478.jpg).

**Comment by uwolfer** [comment]
The plugin uses the same fonts as used everywhere else in IntelliJ (I think so at least). Do these characters get displayed correctly in other places? I think you could switch global IDE fonts in IntelliJ settings.

**Comment by uwolfer** [comment]
@WangDaoO: Please answer my question (see above).

**Comment by wangruihuano** [comment]
@uwolfer 
Sorry to make you wait so long.
Yes,just like you say,I choose another font in IntelliJ settings, and it's worked.
Thank you very much.

The font whose name contains `CN` is supported to display Chinese.

![screenshot from 2018-11-21 18-40-36](https://user-images.githubusercontent.com/26429755/48837155-81fa4880-edbf-11e8-804c-b80bf6c35501.png)
