### ISSUE TITLE
[question] "obtain password" does not reset the HTTP password?

### ISSUE THREAD

**Issue by ericclone** [uwolfer/gerrit-intellij-plugin#333]
So i have two computers. The gerrit plugin stopped working on Computer Bad suddenly. Because it is returning 403 I assumed it is related to account authentication.

But the other Computer, Good, seems to be working fine. (They had the same password when they both worked).

So I went into gerrit settings and in the "HTTP credentials" section I clicked "obtain password" and it gives me this script that configure something something .gitcookies

I copied the password as I did before and pasted it into Computer Bad and it is still giving me 403.

If I go back to Computer Good and put in the "new" password, it stops working, too. If I click the "cancel" and let it revert to its saved password, it works as expected.

Any idea what I did wrong? Is it possible to transfer the password from Computer Good to Computer Bad? Thanks.

**Comment by uwolfer** [comment]
Can you check if password safe settings in both IntelliJ setups are identical? Passwords are not saved in the plugin settings XML, so pruning that XML file (config/options/gerrit_settings.xml) will most probably not help.

The ".gitcookies" part is not a standard Gerrit process IMHO, but I have seen it on gerrit-review.googlesource.com. IIRC the username looks "special" there - ensure that you copy it exactly as displayed directly before the password in the ".gitcookies" line.

I do not know in which file the password is saved (or it is probably not even saved in IntelliJ settings when using a real password manager), but you could try to copy the whole IntelliJ settings folder (.IntelliJ.../config).

**Comment by uwolfer** [comment]
@ericclone: Please post an update if you still can reproduce this issue.
