### ISSUE TITLE
Show git push output contents

### ISSUE THREAD

**Issue by mdindoffer** [uwolfer/gerrit-intellij-plugin#335]
Currently, when a push fails for some reason, only a generic tooltip is displayed.
Users have no way to determine the underlying cause, other than opening a bash terminal and re-running the push command themselves, which ironically defeats the purpose of this plugin.

Trivia: I tried to make our team switch from vanilla git to gerrit thinking this plugin would ease the migration. However, I get called to rescue every other day, because somebody somehow messed it up, can't push the code and the errors are nonexistent.

**Comment by uwolfer** [comment]
This is an IntelliJ functionality - please vote for this feature:
https://youtrack.jetbrains.com/issue/IDEA-82777

**Comment by mdindoffer** [comment]
Voted, thanks.

**Comment by uwolfer** [comment]
> Users have no way to determine the underlying cause, other than opening a bash terminal and re-running the push command themselves, which ironically defeats the purpose of this plugin.

There is a solution which is a bit easier: open the "Version control" tab, and select "Console". There you can see the output of the (failed) push.

**Comment by uwolfer** [comment]
duplicated, see #212
