### ISSUE TITLE
Gerrit missing from "Push Commits" dialog after migration to PyCharm 2019.1.1

### ISSUE THREAD

**Issue by tingey** [uwolfer/gerrit-intellij-plugin#348]
After migrating from from PyCharm 2018.3.5 to 2019.1.1 'Gerrit' is no longer available in the "Push Commits" dialog.

**Comment by uwolfer** [comment]
Duplicate of #345.

**Comment by tingey** [comment]
Thanks for the quick update.  
I'm on macOS 10.14.4 and next available JB JDK below 11 was "JRE: 1.8.0_112-release-b251 x86_64" which has restored the "Gerrit" checkbox!
