### ISSUE TITLE
Support mulitiple Web-Url configuration

### ISSUE THREAD

**Issue by coregiu** [uwolfer/gerrit-intellij-plugin#350]
Recently, I met a problem. That our gerrit code repository are in two web-url, but the gerrit web url configuration only support one web-url. Sometimes, we have to change to Web-Url configuration to review some codes in another repository.
So, I want this gerrit code review plugin support multiple  Web-Url configuration. Thanks!

**Comment by leoluk** [comment]
Duplicate of #159
