### ISSUE TITLE
Open in Gerrit without http port

### ISSUE THREAD

**Issue by ibosong** [uwolfer/gerrit-intellij-plugin#357]
my Gerrit website host in http://xxxx:1081,  which use 1081 server port. When I use "Open in Gerrit" from a change, it open the url without the 1081 port, such as http://xxxx/#/c/1000

![image](https://user-images.githubusercontent.com/4411010/63244199-51ccd100-c28f-11e9-9085-5177320eefbf.png)

**Comment by uwolfer** [comment]
The URL is taken from the plugin config, see:

https://github.com/uwolfer/gerrit-intellij-plugin/blob/intellij14/src/main/java/com/urswolfer/intellij/plugin/gerrit/ui/action/OpenInBrowserAction.java#L51

So I assume this is not correct?

**Comment by ibosong** [comment]
I've already set url with port in the GUI settings, is this correct?
![image](https://user-images.githubusercontent.com/4411010/63480874-33044f80-c4c6-11e9-910c-902b8f2f37fc.png)

**Comment by uwolfer** [comment]
@ibosong: I've just stepped through this code and I think it looks good from the plugin side. Which OS are you using? And which browser gets opened?

**Comment by ibosong** [comment]
I think my gerrit website dispatchs your url from http://gerrit.xxx.xxx/changeNumber to http://gerrit.xxx.xxx/#/c/changeNumber

open the url in the Chrome,  the url shown in the browser has been dispatched:

![image](https://user-images.githubusercontent.com/4411010/63744012-a2b47900-c8d0-11e9-99de-501f1822fb52.png)

It's a pity, my gerrit site cannot login in this entry.  I wonder if your url for a change is the standard format in Gerrit ? I think I should talk about this to the website's admin. Thanks for your reply.

**Comment by uwolfer** [comment]
> I think my gerrit website dispatchs your url from http://gerrit.xxx.xxx/changeNumber to http://gerrit.xxx.xxx/#/c/changeNumber

Yes, this is exactly what happens. This is a standard Gerrit feature I assume. Could it be that in your case the redirection removes the port from the URL?

**Comment by ibosong** [comment]
When I open the url with Edge, the url is exactly in your foramt.
![image](https://user-images.githubusercontent.com/4411010/63994230-74c87200-cb26-11e9-8da3-48b09242c9b2.png)
So I suppose it's a problem of the gerrit server. I cannot login in from this url.
