### ISSUE TITLE
"Cannot show change" if changeset is not checked out locally

### ISSUE THREAD

**Issue by hellfyre** [uwolfer/gerrit-intellij-plugin#364]
The error mentioned in the title occurs when I click on a change in the list of changes. That leads to an empty diff window, the context options on list items however work.

The event log shows two error messages:

1.
> "Error
>	Could not fetch commit because no remote url matches Gerrit host.
>	Git repository: '/home/matthias/repos/somerepo'."
2.
> "Cannot show change: Git error occurred while getting commit. Please check if Gerrit is configured as remote for the currently used Git repository."

The first error is probably due to the fact that the "Web-URL" to the Gerrit server differs from the git URLs.
The 'url' entry of the Gerrit remote in git is "ssh://matthias@chaos.foo.local:22222/somerepo.git".
I tried to set the Clone Base URL almost anything between "ssh://chaos.foo.local" and the whole URL from the git config, which (hopefully) shouldn't matter since you seem to extract the host from those URLs for comparison.

The second error occurs, because the IDEA git implementation tries to 'git show' the commit object representing the changeset I'm trying to view. That of course fails, because that commit object is only on the Gerrit server. If I checkout that particular change (and thereby the associated commit object), I can view the diffs just fine.

There is log output including stack traces for the second error: [idea.log](https://github.com/uwolfer/gerrit-intellij-plugin/files/3656933/idea.log)

I'm not sure if this is maybe a workflow error on my side or if I haven't tried the correct Clone Base URL yet. In any case I I'd be grateful for any input you might have. I'll be happy to provide more debugging information, if you need anything.

Plugin version: 1.1.2.1-146 (from Marketplace)

IntelliJ IDEA 2019.2.2 (Ultimate Edition)
Build #IU-192.6603.28, built on September 6, 2019
Runtime version: 11.0.3+12-b304.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-29-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1927M
Cores: 8
Registry: ide.editor.tabs.open.at.the.end=true
Non-Bundled Plugins: IdeaVIM, Statistic, com.intellij.apacheConfig, com.ritesh.intellij.plugin.reviewboard, com.tang, com.urswolfer.intellij.plugin.gerrit, ideanginx9, com.perl5, com.intellij.plugins.html.instantEditing, com.jetbrains.php, org.jetbrains.plugins.phpstorm-remote-interpreter, Pythonid, org.majki.intellij.ldapbrowser

**Comment by uwolfer** [comment]
@hellfyre: I think this issue could be resolved with this change: https://github.com/uwolfer/gerrit-intellij-plugin/commit/c716b70ae8942bfb4517357c782eab4857dbc034

It will be included in the next release. Please let me know if it helps when the next release is out.

**Comment by hellfyre** [comment]
Yes, that solves it. Thank you!
