### ISSUE TITLE
Add support for .gitcookies login

### ISSUE THREAD

**Issue by thughes** [uwolfer/gerrit-intellij-plugin#365]
The chromium project uses a `.gitcookies` file to authenticate with Gerrit: https://dev.chromium.org/chromium-os/developer-guide/gerrit-guide.

The `.gitcookies` file is a Netscape HTTP Cookie file: https://curl.haxx.se/docs/http-cookies.html.

This file shows how to authenticate with the `.gitcookies` file: https://android.googlesource.com/platform/development/+/master/tools/repo_pull/gerrit.py#45

Would it be possible to add support for this in the Gerrit plugin so Chromium developers can use it?

**Comment by uwolfer** [comment]
@thughes: This affects only Google-internal setups of Gerrit, right? Public Gerrit instance (e.g. https://chromium-review.googlesource.com/) should work fine with this plugin.

**Comment by thughes** [comment]
No, I believe it affects the public one (at least when I tried it a few
months ago), since it uses the same login mechanism.

**Comment by uwolfer** [comment]
@thughes: I'm able to connect to gerrit-review.googlesource.com by setting HTTP credentials. Can you please try if that works for your instance as well?

**Comment by thughes** [comment]
@uwolfer Did you try against the Chromium gerrit instance: https://chromium-review.googlesource.com/?

It looks like you might have authenticated against the "Gerrit" Gerrit instance, which may have different settings. It appears that the Chromium instance is configured to only allow `.gitcookies` credentials: https://www.chromium.org/developers/gerrit-guide

**Comment by uwolfer** [comment]
@thughes: I've just tried the plugin against https://chromium-review.googlesource.com/ and it works fine.

It works the same way as https://gerrit-review.googlesource.com/

It's a bit of manual work to do:
`Settings` -> `HTTP Credentials` -> `Obtain password`
Then search for the line in the text area starting with `chromium-review.googlesource.com` and extract username and password:
chromium-review.googlesource.com,FALSE,/,TRUE,12345678,o,**git-username.gmail.com**=**password-until-end-of-line**

You probably want to add a note to your documentation how to get this task done?

If you expect "better" support in this plugin, how would you implement it into the UI?

**Comment by thughes** [comment]
Thanks, that does work. I thought I had tested that, but I guess not. Thanks for updating the README.

**Comment by kartynnik** [comment]
To clarify, that line in the `Obtain password` field is precisely what ends up in the `.gitcookies` file.
