### ISSUE TITLE
Support for Multiple Web URLs

### ISSUE THREAD

**Issue by wTylerReid** [uwolfer/gerrit-intellij-plugin#369]
I use multiple GoB Hosts for my development.  Could we add a feature which supports multiple Web URLs from the settings page?

Let me know if you need any more details!

**Comment by uwolfer** [comment]
Do you need multiple Gerrit instances per project? Or one per IntelliJ project?

**Comment by wTylerReid** [comment]
One per IntelliJ Project.

**Comment by uwolfer** [comment]
Duplicate of #159.
