### ISSUE TITLE
How to perform "Reply" action

### ISSUE THREAD

**Issue by archmisha** [uwolfer/gerrit-intellij-plugin#370]
Hi,
I have added multiple comments on a pull request. 
In gerrit is shows as draft and I need to click "Reply" there to submit the comments so others can view them.
Is there a way to do that from within the plugin?

**Comment by uwolfer** [comment]
When you open a file diff, you can see comments as line annotations (icons on the left or right of a line). When you click on such an icon, you can choose to reply. Is this what you are looking for?

**Comment by archmisha** [comment]
Found out i can do review 0 and it will submit the comments
