### ISSUE TITLE
How to submit unresolved comment?

### ISSUE THREAD

**Issue by archmisha** [uwolfer/gerrit-intellij-plugin#372]
Gerrit rest api describes an option to submit unresolved comment by providing unresolved flag in the body of the request as specified here: https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#comment-input

Looks like the plugin doesn't use this flag and the result is that all comments submitted resolved.

Can the resolved flag be supported?

**Comment by thughes** [comment]
Even if the resolved flag cannot be toggled, it would be nice to default to "unresolved" since that's what the Gerrit web UI does.
