### ISSUE TITLE
Owner shows null

### ISSUE THREAD

**Issue by rymurr** [uwolfer/gerrit-intellij-plugin#379]
Hey,

First, thanks a lot for the awesome plugin. :+1: 

I am able to connect to my gerrit instance and see all changes but a lot of fields are empty: Owner, Reviewer, Patch Set, Status etc.

I am on gerrit 3.1.3 and the Intellij 2020.1 Beta

**Comment by uwolfer** [comment]
Is it possible to create an (anonymized) screenshot? Did it work it an older version of the plugin / IntelliJ? I've never heard of such an issue...

**Comment by rymurr** [comment]
![20200322-132021_censored](https://user-images.githubusercontent.com/2022305/77249301-649dee80-6c40-11ea-912d-949dd9ad5b29.jpg)

note owner is set to null and empty in the table. Filtering on owner, Reviewer etc has no effect. Also note the diff on the far right is not loading either. 

I have been getting this for a month or two (so a handful of Intellij EAPs). Prior it didn't work at all as I was using an ancient verison of Gerrit.

**Comment by rymurr** [comment]
![20200322-132021_censored (1)](https://user-images.githubusercontent.com/2022305/77249385-045b7c80-6c41-11ea-8323-3b4df0474b28.jpg)

As you can see the Owner field is null. Filtering on owner doesn't produce any result. Same as filtering on Reviewer etc. These definitely have values set on the gerrit ui

This has been happening for a few months. So I would have gone through several versions of the gerrit plugin and several versions of IDEA.  It has never worked as prior to this I had an ancient Gerrit version and I couldn't get the tool to work at all.

**Comment by uwolfer** [comment]
Thanks. I still have no clue what happens here. Can you check the requests which are done by the Gerrit web UI in the browser network debugging tool and check if they contain all the information? Also, do you have Gerrit 3.1.3 release or a snapshot build?

**Comment by rymurr** [comment]
Hey @uwolfer 

Looks like the UI is getting its details from: `https://<SERVER>/gerrit/changes/<REPO>-<CHANGE_ID>/detail?O=<CHANGE_ID>`

`gerrit version` gave `3.1.3` so I assume its the release rather than a snapshot.

**Comment by uwolfer** [comment]
Thanks @rymurr for your feedback. Unfortunately I still have no clue what's going on in your case.

What type of authentication do you use (if you are not using HTTP credentials from Gerrit settings, you could try that)? Do you probably know if coworkers do have the same issue?

**Comment by rymurr** [comment]
Hey @uwolfer this is indeed using the HTTP credentials in the gerrit settings. We use oauth for normal authentication and the gerrit site is on a VPN.

**Comment by rymurr** [comment]
Is there a cache of gerrit data/settings being saved somewhere by this plugin? I was thinking of doing a purge of that cache

**Comment by uwolfer** [comment]
Config is saved at `intellij-settins-folder/config/options/gerrit_settings.xml.`

You could also try to (manually) install an old version of the plugin which is compatible with your IntelliJ version: https://plugins.jetbrains.com/plugin/7272-gerrit/versions (just download the zip and install it manually from the plugin manager).

**Comment by rymurr** [comment]
hey @uwolfer 

Unfortunately no luck. I have added your rc repo and will keep an eye on if the plugin magically starts working in the future.

**Comment by rymurr** [comment]
Not sure if this is helpful but I notice that the pane to the right of the open patches (with 'Diff against:' at the top left) is always stuck on 'Loading...' so I am never able to look at patches either.

**Comment by rymurr** [comment]
Aha! I figured it out. My bookmark was pointing to an alias `x.company.com` which redirects to `gerrit.company.com`. When I switched to `gerrit.company.com` it started to work! So perhaps the issue is simply that the plugin doesn't follow 302 redirects?

**Comment by uwolfer** [comment]
@rymurr: Great news! Thanks for keeping me updated. Yes, it is possible that the plugin does not follow redirects. But still, it is strange that it display "something" (change with missing details...). I have no idea why this happens. But I don't think I'll find the time to investigate this corner case.
