### ISSUE TITLE
Plugin stopped working after Gerrit update.

### ISSUE THREAD

**Issue by klaucos** [uwolfer/gerrit-intellij-plugin#384]
Error started happening after Gerrithub updated to new version and doesn't stop even after updating http credentials.

```
Request not successful. Message: Forbidden. Status-Code: 403. Content:
403 Forbidden
Request forbidden by administrative rules.
```

Used as v.1.2.2.-146 of a Pycharm plugin: https://plugins.jetbrains.com/plugin/7272-gerrit

**Comment by uwolfer** [comment]
@klaucos: Please update the plugin to the latest version (do so in the IntelliJ plugin manager).
