### ISSUE TITLE
Unable to connect plugin to gerrit (ssh and VPN config)

### ISSUE THREAD

**Issue by JR-Utily** [uwolfer/gerrit-intellij-plugin#386]
Hello,

Context: We have just moved our gerrit server from a local machine to a remote server managed by kubernetes and reachable through a VPN managed by kubernetes too :)

Everything was working fine before. Regular usage of gerrit through command line only needed to change .git/config. But the IntelliJ plugin is not working anymore.

```
$ git remote -v
gerrit	ssh://user@gerrit.hw-ci:29418/company (fetch)
gerrit	ssh://user@gerrit.hw-ci:29418/company (push)
origin	git@bitbucket.org:company/company.git (fetch)
origin	git@bitbucket.org:company/company.git (push)
```

Web interface is accessible through:
`http://gerrit.hw-ci.svc.cluster.local/` or `http://gerrit.hw-ci/`
(We have a search domain in our VPN DNS making "gerrit.hw-ci.svc.cluster.local" url be shortened in "gerrit.hw-ci")

In command line, I can git review, git review -d 1000, git review -l, etc.
Our gerrit web server has no options for http password, but I can set it with 
`$ ssh -p 29418 -l user gerrit.hw-ci gerrit set-account --generate-http-password user`

In IntelliJ, I can push to gerrit and it successfully push on refs/for/master with correct reviewers and topics.

But the plugin itself can't connect to gerrit server, neither in configuration panel, neither to download change list.
![image](https://user-images.githubusercontent.com/1372453/85587515-23075000-b642-11ea-8922-ef90438e87d3.png)
And I got this error message when clicking Test button:
![image](https://user-images.githubusercontent.com/1372453/85587326-fce1b000-b641-11ea-8e8e-eebe1942e33c.png)
What is interesting, is that if I change the password field, then the error message changed to a 401, meaning that in previous test, authentication is correct, but something else is wrong... 
![image](https://user-images.githubusercontent.com/1372453/85587425-0f5be980-b642-11ea-9e83-8d8bebd131b6.png)

Before our cloud migration, the password was to be the one from the normal Web sign-in. This is the one that "works" (no 401) here too. The password given by the  `ssh ... --generate-http-password` never worked for me.

I don't know how to get a more precise error message to understand what could be the problem. I have also tried with http://gerrit.hw-ci.svc.cluster.local as Web URL with no luck.

**Comment by uwolfer** [comment]
> The password given by the ssh ... --generate-http-password never worked for me.

I've never used this command, but it sound like this does the same as when you generate a HTTP password in the Gerrit web UI settings? But still, could you try to get a HTTP password from the web UI and try using this in the plugin?

**Comment by JR-Utily** [comment]
Thanks for the reply !
The problem is that this option is not available in our server, I don't know why
![image](https://user-images.githubusercontent.com/1372453/85676505-f21d2e80-b6c6-11ea-824a-b490b4787c6e.png)

**Comment by uwolfer** [comment]
> The problem is that this option is not available in our server, I don't know why

I've never seen such a setup - and I unfortunately have no idea how to "fix" it. Probably this is a Gerrit server config? Please post any updates here, as it probably will help other users in the future as well.

**Comment by JR-Utily** [comment]
Hello,
So, in fact, it "works" with my regular web credentials ;)

But there are a lot of timeout (I think) from the distant server and so the plugin give this error message without more details.
If I try several time to refresh the change list or to checkout one specific change, it fails at first request then work. 

It may be convenient to have a parameter to set the max timeout period before a request fail, what do you think ?
