### ISSUE TITLE
Unable to connect to Gerrit server.

### ISSUE THREAD

**Issue by oransherf** [uwolfer/gerrit-intellij-plugin#389]
Hi,

I'm trying to connect to a Gerrit server via GUI panel on PyCharm but I got an error.
My login info:
![image](https://user-images.githubusercontent.com/45199829/95081920-f07df080-0722-11eb-8578-201a528d3cd1.png)

The error I got:
![image](https://user-images.githubusercontent.com/45199829/95082101-3aff6d00-0723-11eb-8fc3-ba46645ad631.png)

I think it happening because the Gerrit URL I'm trying to connect is from the pattern: https://XXXXX:port.

Any suggestions?

Thanks,
Oran

**Comment by uwolfer** [comment]
@Orans94: What version of PyCharm are you using? Have you tried this plugin with a previous version of PyCharm?

**Comment by oransherf** [comment]
> @Orans94: What version of PyCharm are you using? Have you tried this plugin with a previous version of PyCharm?

I'm using PyCharm 2020.1 (Professional Edition), I have not tried this plugin in any previous versions of PyCharm.

**Comment by uwolfer** [comment]
Can you try to connect to a public Gerrit server like https://gerrit-review.googlesource.com/? Then we can see if this issue is related to your (authentication) setup.

Also: what JRE are you using for PyCharm?

**Comment by oransherf** [comment]
The problem was solved.
There was an issue with my HTTP proxy setting, after fixing it, I was able to connect successfully.
