### ISSUE TITLE
Support review state

### ISSUE THREAD

**Issue by leonard84** [uwolfer/gerrit-intellij-plugin#390]
Gerrit tracks which files you have looked at and marks them as reviewed, this feature is sorely missing from the plugin.
I currently have to review a massive change ~4600 files, as gerrit is noticeably slower it is a prime usecase for this plugin.
Unfortunately the plugin doesn't keep track of what files I already reviewed, which is quite important in such a large change.

Furthermore, it would be nice if one could filter the file list to show only the unreviewed files.

**Comment by uwolfer** [comment]
I think the plugin should already set the reviewed state - are you sure this doesn't work in your case? See relevant code line: https://github.com/uwolfer/gerrit-intellij-plugin/blob/7a1dddc5f8af17e537772113fb8e591edad9bdd0/src/main/java/com/urswolfer/intellij/plugin/gerrit/ui/diff/CommentsDiffTool.java#L203

**Comment by leonard84** [comment]
@uwolfer you are right the flag is set on gerrit, but it isn't shown in the diff list in Intellij, that is why I was assuming that the plugin didn't support it at all. Furthermore, gerrit allows to set the review state either in the list, or in the diff view, e.g., when you didn't finish reviewing the file.

So I'd clarify that the plugin should display the review state, support filtering by review state to show only unreviewed files and allow to manually toggle it.

**Comment by uwolfer** [comment]
@leonard84 Thanks for your feedback. This feature request is tracked in #20.

**Comment by leonard84** [comment]
Ok that issue is from 2013 any chance this can be implemented?

**Comment by uwolfer** [comment]
@leonard84: Would be nice if we could get that implemented - as this is an open source project, anybody can contribute. My spare time at the moment is unfortunately quite limited.

**Comment by leonard84** [comment]
@uwolfer I hear you, limited spare time is a problem we have in common.

I'm not against helping, but the code base of this plugin and the gerrit client is quite complex and I couldn't figure out where I could obtain the review state. From what I could see https://github.com/uwolfer/gerrit-intellij-plugin/blob/intellij14/src/main/java/com/urswolfer/intellij/plugin/gerrit/ui/GerritCommentCountChangeNodeDecorator.java is the class responsible to render the changes tree, where I would put the reviewed indication.

**Comment by uwolfer** [comment]
@leonard84: Thanks for your offer! I'm happy to support this work.

In order to get a working dev setup, I hope the README should help. If you miss any parts there, please let me know.

`GerritCommentCountChangeNodeDecorator` seems to be a good entry point. In that class at the very bottom, you can also see some data fetching for draft comments. I've not looked into details yet, but I'd suppose that you can just fetch the review state in a similar way:

```java
gerritApi.changes()
  .id(selectedChange.id)
  .revision(getSelectedRevisionId())
  .reviewed()
```
Does this already answer your question?

**Comment by leonard84** [comment]
@uwolfer this project still uses gradle 4.4, whereas gradle 6.7 is the latest version. Is there a reason not to update?

**Comment by uwolfer** [comment]
> @uwolfer this project still uses gradle 4.4, whereas gradle 6.7 is the latest version. Is there a reason not to update?

Good point - I think we can update it.

**Comment by uwolfer** [comment]
> @uwolfer this project still uses gradle 4.4, whereas gradle 6.7 is the latest version. Is there a reason not to update?

Updated now. Please rebase your PR.
