### ISSUE TITLE
it happens to ask me to inpput gerrit password everytime when I open the IDE

### ISSUE THREAD

**Issue by rockingGitHub** [uwolfer/gerrit-intellij-plugin#395]
Its a nice plugin. But in idea2020.1, it happens to ask me to inpput gerrit password everytime when I open the IDE, I dont know what`s happen

**Comment by uwolfer** [comment]
@rockingGitHub Probably this solution helps in your case? https://github.com/uwolfer/gerrit-intellij-plugin/issues/393
