### ISSUE TITLE
Can not use Review and Add Reviewers option. 404 Content Not found

### ISSUE THREAD

**Issue by d3bowy** [uwolfer/gerrit-intellij-plugin#413]
Hello, In settings connection passed, but when I am trying to use review or add review I receive an error, i.e.:
com.urswolfer.gerrit.client.rest.http.HttpStatusException: Request not successful. Message: Not Found. Status-Code: 404. Content: Not found: xxx

**Comment by uwolfer** [comment]
@d3bowy: Is this a new issue (i.e. did it work before the last update of the plugin)?

**Comment by d3bowy** [comment]
No, I just have tried to set up it the very first time, but these options do not work from the context menu.

**Comment by d3bowy** [comment]
I have multiple projects ( using "repo" tool  for this ) I do not know if it can cause any problem

**Comment by uwolfer** [comment]
I assume listing the changes does work, because otherwise the actions in the context menu would not be available. What is the version of the Gerrit server?

**Comment by d3bowy** [comment]
In the bottom right corner, I see "Powered by Gerrit Code Review (2.15.5)"  so I guess this is a problem...

**Comment by uwolfer** [comment]
Oh, that is pretty outdated. Gerrit 2.15 is [end of life](https://www.gerritcodereview.com/2019-11-15-gerrit-2.15-eol.html) for quite some time already. I don't think I'll find the time to investigate issues with such old Gerrit version.

Would be nice if you could get your admin to update your Gerrit server. Please report back it this issue still exists with a recent Gerrit version.

**Comment by d3bowy** [comment]
Ok, thank you very much for your help!
