### ISSUE TITLE
Cannot get Gerrit plugin to work with Intellij.  "Failed to get Gerrit changes: Request failed"

### ISSUE THREAD

**Issue by christophermazza** [uwolfer/gerrit-intellij-plugin#415]
When I go into the Settings for my gradle project, under Version Control/Gerrit, when I click the "Test" button, I always get the same error message:

Can't login to"...": com.google.gerrit.extensions.restapi.RestApiException: Request failed.

Using IntelliJ IDEA 2021.1.3 (Community Edition).
Plugin version 1.2.5-203.
Language JAVA.

This *used* to work.  Recently we updated our version of IntelliJ and the Plugin.

thank you!

**Comment by uwolfer** [comment]
Is https://git.epyonpower.com:8445/ the URL for accessing Gerrit? Is there no sub path? Also, try removing the trailing #.

**Comment by christophermazza** [comment]
Yes,  "..." is the URL.  No sub path.  Tried without trailing #, no difference.
Could it be a certificate issue?  in the browser, it indicates "connection not secure".

**Comment by uwolfer** [comment]
You could try to downgrade plugin. You can manually download an older release from GitHub releases and install in IntelliJ from Zip.
