### ISSUE TITLE
Cherry pick a merge commit fails

### ISSUE THREAD

**Issue by forrert** [uwolfer/gerrit-intellij-plugin#42]
I tried to use the "Cherry Pick" action on a merge commit and got the following error:

    7:35:51 AM Cherry-Pick Error
               error: Commit 6076f2987fcb7e108a293ebdd22d8926e2330451 is a merge but no -m option was given.
               fatal: cherry-pick failed

The version control console shows the following commands:

    07:40:56.995: git fetch --progress origin refs/changes/33/6433/1
    From ssh://git.XXX.ch:29418/YYY
     * branch            refs/changes/33/6433/1 -> FETCH_HEAD
    07:40:58.585: git cherry-pick -x -n 6076f2987fcb7e108a293ebdd22d8926e2330451
    error: Commit 6076f2987fcb7e108a293ebdd22d8926e2330451 is a merge but no -m option was given.
    fatal: cherry-pick failed

**Comment by uwolfer** [comment]
Merge-commits can only be checked out. There is now an action available for doing this.
