### ISSUE TITLE
Link Gerrit credentials to IDEA projects instead of applying them globally

### ISSUE THREAD

**Issue by kriegaex** [uwolfer/gerrit-intellij-plugin#421]
I work on dozens of IDEA projects and need Gerrit only for a single one, a forked Eclipse project. Even there, I only need it when contributing one of my bugfixes to the upstream project because Eclipse requires PRs in Gerrit. Nevertheless, the Gerrit plugin always tries to connect to the server when starting the IDE or re-opening unrelated projects. It also shows me notifications about pending reviews completely out of context in projects not using Gerrit. This becomes even more useless when I get curious, opening the Gerrit view, but seeing nothing of course, due to the fact that 99% of my projects do not use Gerrit and my pending reviews etc. are only displayed when I open the right project with the right Git connection.

I think that this is a design flaw. Gerrit server URLs and credentials should be per project, so that the plugin does not do anything when the corresponding project does not use Gerrit but e.g. GitHub or whatever SCM. And what if two different OSS or commercial projects use different Gerrit servers, for example one company server and one OSS one for Eclipse?

**Comment by uwolfer** [comment]
I think this is a duplicate of #159. If you do not agree, please let me know.

**Comment by kriegaex** [comment]
I agree. I am going to transfer the issue text as a comment to the other issue.
