### ISSUE TITLE
Gerrit plugin for IntelliJ running inside WSL 2 as a GUI app does not remember http credentials

### ISSUE THREAD

**Issue by mdzhigarov** [uwolfer/gerrit-intellij-plugin#431]
***What steps will reproduce the issue?***
Microsoft Windows [Version 10.0.22000.493]
WSL 2 kernel version 5.10.60.1
Ubuntu 20.04
[IntelliJ 2021.3.2 running inside WSL 2 as a GUI app](https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps) executed as a standalone (/opt/\<idea-dir\>/bin/idea.sh)
Installed the Gerrit plugin for IntelliJ

![](image.png)
2\. Set an http password for Gerrit. Click Test - connection is established successfully.
3\. Close the IDE from File -\> Exit
4\. Open the IDE again (/opt/\<idea-dir\>/bin/idea.sh). Click Test button again - the credentials are no longer valid and you get http 401 unauthorized.
Seems the stored password is different.
***What is the expected result?***

Gerrit plugin should continue to work without having to re-set the password

***What happens instead?***

The Gerrit plugin no longer works and one has to manually re-set the password and click Apply. 
Once the IDE is closed and opened again (doesn't matter if done immediately or after i.e. 5 hours) - the password setting is lost again.
Issue reproduced at around 13:30 in the logs
[log.zip](https://github.com/uwolfer/gerrit-intellij-plugin/files/8132152/log.zip)

**Comment by uwolfer** [comment]
@mdzhigarov: Can you please check our password settings in IntelliJ settings? Have you enabled persistent password storage?

**Comment by mdzhigarov** [comment]
Actually, that's exactly the issue. Thank you @uwolfer for the help! 
I had no idea this thing existed
