### ISSUE TITLE
Cannot use plugin: java.lang.IllegalStateException: Expected NUMBER but was BEGIN_OBJECT at path $.labels.

### ISSUE THREAD

**Issue by Javanut2158** [uwolfer/gerrit-intellij-plugin#451]
While reviewing, adding reviewers etc, plugin fails with the message "java.lang.IllegalStateException: Expected NUMBER but was BEGIN_OBJECT at path $.labels.".  Using IntelliJ Idea 2022.1.3 Ultimate Build #IU-221.5921.22, built on June 21, 2022 (but it fails in previous editions as well - for about a six weeks now).  Gerrit plugin version 1.2.6-203. Using Gerrit code review version 3.2.3. Previously have used this plugin for some time with various versions with no issue. Any idea what is up?

**Comment by uwolfer** [comment]
This looks like the REST endpoints return an unexpected (non-JSON) result. Does the "Test" button in plugin settings work as expected?

**Comment by Javanut2158** [comment]
I only see 'disable' or 'uninstall' in the settings within the plugin. Where is it?

**Comment by uwolfer** [comment]
Please check the plugin settings under Version Control -> Gerrit

**Comment by Javanut2158** [comment]
Connection successful

**Comment by uwolfer** [comment]
Do all requests fail? Or does for example listing changes work?

**Comment by Javanut2158** [comment]
I can certainly see any changes, like if I +1 to a change in the web version, it shows in the IDE. But it seems that any info that I am adding does not succeed. Acting like it's read-only or something. But I have the full permissions in the web version (that hasn't changed for years)

**Comment by Javanut2158** [comment]
Well we figured it out. Our company changed our Gerrit servers from http to https, so I just needed to update the Gerrit url in settings to reflect the https protocol. Thanks for your help!
