### ISSUE TITLE
"C" shortcut in diffs does not work anymore

### ISSUE THREAD

**Issue by leoluk** [uwolfer/gerrit-intellij-plugin#459]
Pressing "C" to add a comment to a selection in a patch no longer works:

<img width="441" alt="image" src="https://user-images.githubusercontent.com/859697/189904408-5f8f9d33-8a06-42c9-a771-44a44778b02d.png">

Context menu still works.

**Comment by uwolfer** [comment]
Duplicate of #410. Unfortunately that one is open for quite some time :(
