### ISSUE TITLE
IDE not showing comments made using the browser

### ISSUE THREAD

**Issue by ssadoun** [uwolfer/gerrit-intellij-plugin#463]
Hello,

First of all, I wanted to thank you for the plugin. It's really helpful!

My issue is that the PyCharm IDE does not show any comments made using the browser.
I'll note that a lot of other things are visible. For example, the ACS, ACM, CR, RfP, RfR, and V flags change accordingly.
Now I might be missing something here, but it seems like the plugin doesn't pull the comments made using the browser GUI.
However, If I open the commit file diff and try to add a new comment, I do see it 🤔

Gerrit v3.5.0.1
PyCharm v2022.1.3 (Community Edition)
Gerrit Plugin v1.2.6-203

**Comment by leoluk** [comment]
Are the missing comments drafts or submitted?

**Comment by ssadoun** [comment]
Both are not visible.

**Comment by uwolfer** [comment]
Which diff viewer are you using in PyCharm? Probably you could switch to the old one (side by side), and check if comments show up in that case.

**Comment by ssadoun** [comment]
> Which diff viewer are you using in PyCharm? Probably you could switch to the old one (side by side), and check if comments show up in that case.

I'm using the default diff viewer Pycharm has

**Comment by uwolfer** [comment]
@ssadoun Could you please post a screenshot of the diff viewer?

**Comment by ssadoun** [comment]
![PyCharm_Diff_Viewer](https://user-images.githubusercontent.com/101505031/204567849-0161be44-f373-4510-913d-727da453ebab.png)

@uwolfer 
There is a comment next to line #62 in Gerrit web UI, but it is missing here...

**Comment by ssadoun** [comment]
@uwolfer ?

**Comment by uwolfer** [comment]
@ssadoun Sorry for the late response. This sounds really odd, I cannot see the issue. Can you see comments created by others? What happens if you add a comment in IntelliJ, and submit it? Does it still appear after you close the diff viewer and open it again (to make sure, you probably even could restart IntelliJ).

**Comment by ssadoun** [comment]
@uwolfer 
I cannot see comments created by others, nor can I add a comment by myself.
That is the reason I created this issue in the first place.

I'm using PyCharm, not IntelliJ. Please see the image attached.

**Comment by uwolfer** [comment]
> I'm using PyCharm, not IntelliJ. Please see the image attached.

Yes, I have read that. PyCharm is also based on the IntelliJ platform. For that reason, you can also apply my sentence to PyCharm:

> What happens if you add a comment in PyCharm, and submit it? Does it still appear after you close the diff viewer and open it again (to make sure, you probably even could restart PyCharm).

**Comment by ssadoun** [comment]
@uwolfer I think I understand the problem now. No comments were shown when I used "Repository Diff", but when I used "Open Diff" via the Gerrit plugin, they could be viewed, replied to, and marked as complete.
