### ISSUE TITLE
How to push to Gerrit without displaying the push dialog

### ISSUE THREAD

**Issue by lisa-han** [uwolfer/gerrit-intellij-plugin#478]
How to push to Gerrit without displaying the push dialog?

**Comment by uwolfer** [comment]
Can you please explain the motivation of this request?

**Comment by lisa-han** [comment]
> Can you please explain the motivation of this request?

My boss wants the Commit and Push button to directly push to Gerrit without displaying the push dialog when clicked.
I don't know how to implement this.

**Comment by lisa-han** [comment]
![image](https://user-images.githubusercontent.com/59714816/231912020-011373e9-54e7-4d9c-a1eb-e18e48b615a0.png)
click the button "Commit and Push"  to directly push to Gerrit without displaying the push dialog

**Comment by lisa-han** [comment]
![1680776964561](https://user-images.githubusercontent.com/59714816/232005614-762664ef-5044-4d6c-b60d-75bd630ccf1d.png)
Click the "Commit and push to gerrit" button in the image to directly push changes to gerrit without displaying the push dialog.

 I don't know how to update the push target from origin to refs/for.
