### ISSUE TITLE
push with error  

### ISSUE THREAD

**Issue by gakkiismywife** [uwolfer/gerrit-intellij-plugin#482]
error: failed to push some refs to 'http://127.0.0.1:3000/root/test.git'

the `http://127.0.0.1:3000/root/test.git` is origin git repository. the gerrit url is `http://127.0.0.1:8801` and I test connnect is success

**Comment by uwolfer** [comment]
I assume this error is not related to the plugin. Please try again without the plugin. If it works that way, please report back.

**Comment by gakkiismywife** [comment]
> I assume this error is not related to the plugin. Please try again without the plugin. If it works that way, please report back.

I push without gerrit was succeed. But I push to gerrit was failed.
