### ISSUE TITLE
Test connect error

### ISSUE THREAD

**Issue by zephyrcicd** [uwolfer/gerrit-intellij-plugin#521]
<img width="888" alt="image" src="https://github.com/user-attachments/assets/2603d6f1-6db9-4748-bdba-8438aa4a8a75">
Can't login to http://gerrit.xxxxx.com: com.google.gerrit.extensions.restapi.RestApiException: Request failed

IDEA Version: IntelliJ IDEA 2024.2.3 (Ultimate Edition)

OS：MacOS 15.1

It seems to have happened after I updated from macos15.0.1 to 15.1, there were no problems before that.

**Comment by uwolfer** [comment]
Hard to say what the issue is. Is the SSL certificate valid? Can you please remove and re-enter the password?

**Comment by zephyrcicd** [comment]
> Hard to say what the issue is. Is the SSL certificate valid? Can you please remove and re-enter the password?

Yes, I tried re-entering my account password, but it didn't work.
My gerrit server has not set SSL certificate.

**Comment by zephyrcicd** [comment]
I found that the problem was caused by the proxy settings in my IDEA!
